### ISSUE TITLE
cache decorator causes issues with memory leak

### ISSUE THREAD

**Issue by PJCampi** [tkem/cachetools#106]
Hey tkem,

Consider the following naive example:

```
from cachetools.func import lfu_cache

class Foo(object):
    @lfu_cache(100)
    def bar(self):
        pass

foo = Foo()
foo.bar()
```

`foo` will not be properly garbage collected because it is still referenced as part of a key inside the cache.

```
import gc
gc.collect()
referrers = gc.get_referrers(foo)
assert 1 == len(referrers)
```

Is there a recommended approach to decorating a method? I can use `cachemethod` with a `key` function that excludes the instance inside the hash, but is there a preferred way?

Thank you,

PJ

**Comment by tkem** [comment]
Yes, that's what the `@cachedmethod` decorator is for.

**Comment by tkem** [comment]
Well, I could have sworn that `self` wasn't passed to the `key` function when using `@cachedmethod`...
However, when using the "recommended approach" as outlined in the docs, there should be no memory leak with `@cachedmethod`, for example:
```
import gc
import operator
from cachetools import LRUCache, cachedmethod

class Foo(object):
    def __init__(self, cachesize):
        self.cache = LRUCache(maxsize=cachesize)

    @cachedmethod(operator.attrgetter('cache'))
    def bar(self):
        print('Foo.bar called')

    def __del__(self):
        print('Foo destructor called')


def test():
    foo = Foo(100)
    foo.bar()
    foo.bar()
    foo.bar()

print('Calling test')
test()
print('Before gc.collect')
gc.collect()
print('After gc.collect')
```
prints (on Python 3.6.5, at least):
```
Calling test
Foo.bar called
Before gc.collect
Foo destructor called
After gc.collect
```

**Comment by PJCampi** [comment]
Thanks for the answer Thomas.

I thought that the reason for including `self` in the `key` function was to make `cachemethod` as generic as possible? It allows for class level or instance level caching.

**Comment by tkem** [comment]
Well, not really IMHO. The `cache` parameter to `@cachedmethod` is a function that is passed `self`, so you can already decide whether you want to cache this at the instance or class level, or in some global cache, or whatever. At least that's how I envisioned using it, so using `self` as a key argument is somewhat redundant. It may also lead to surprises if your class/instance is not hashable, e.g. if you derive from `dict` or override the `__hash__` method in your class. See also #107 for more thoughts on this. If you'd like to comment on that, your input would be appreciated!

**Comment by PJCampi** [comment]
Good point.

**Comment by tkem** [comment]
Can we close this? IMHO there's no real memory leak, and `self` is going to be removed from the `@cachedmethod` arguments in cachetools v3.0.

**Comment by PJCampi** [comment]
Sure. I realise now that I mistook the referrers count as a sign of memory leak. Sorry about that. Good that something came out of it though ;)

**Comment by PJCampi** [comment]
Regarding whether `self` should be added to the list of arguments of the `key` function. You may actually need it to call a `to_key` method on the class e.g.:

```
@cachedmethod(operator.attrgetter('cache'),
              key=lambda s, *a, **kw: operator.methodcaller('to_key', a, kw)(s))
```

**Comment by tkem** [comment]
Good point! I'll take it into consideration, although I'd assume that use case is somewhat rare and quite special.

**Comment by tkem** [comment]
@PJCampi: Regarding your last comment, I think this could be solved with another level of indirection, if need be:
```
def foo(self, *args, **kwargs):
    return _foo(self, self, *args, **kwargs)

@cachedmethod(operator.attrgetter('cache'),
              key=lambda s, *a, **kw: operator.methodcaller('to_key', a, kw)(s))
def _foo(self, s, ...):
    ....
```
Maybe not elegant, but as stated before I consider this a rare (and maybe questionable) use case.

**Comment by dpinol** [comment]
Related to https://github.com/python/cpython/issues/102618
