### ISSUE TITLE
@cachedmethod: Remove 'self' from key arguments

### ISSUE THREAD

**Issue by tkem** [tkem/cachetools#107]
The whole point of the `cache` argument of `@cachedmethod` being a function is to select an appropriate cache for `self`. So there is little to no reason for passing `self` to the `key` function. This was simply an oversight when preparing for cachetools v2.0.0.

Main question is: is this merely an ordinary bug, or a breaking change which would have to wait until cachetools v3.0.0?

**Comment by tkem** [comment]
Also note that this breaks somewhat surprisingly if `self` is not hashable.

**Comment by lmignon** [comment]
@tkem I discover this change today with the upgrade of cachtools to 3.0.0. I'm a little bit disappointed by this change. My understanding of the `key` argument is to give a way to provide its own method to build the key used to store and retrieve the result of the call to the method. In our use of this argument, we provide methods where we collect information on `self` to build a 'hashable` key.
```python
 @cachedmethod(operator.attrgetter('_cache'),
                  key=lambda self, name: keys.hashkey(
                      self.work.collection._name
                      if self.work._collection is not None else None,
                      self.work.model_name,
name)
```
With your change it's no more possible.... 
I don't understand the problem you're trying to solve with this fix and how we can now achieve the same result.

**Comment by tkem** [comment]
Reasons were stated above (arguably unexpected behavior, breaks if `self` is not hashable).
I'm afraid I don't understand your example - why would you make a cache key depend on instance attributes? What if these change? Why not pass `work` as an argument to the cached method?

**Comment by lmignon** [comment]
Maybe a miss understanding on my side but IMO the method provided with the `key`argument is always called with the real instance not a cached one. I understand that the result must be hashable but not the parameters.
Do I miss something?

**Comment by tkem** [comment]
Yes, the default case where you don't provide a custom `key` function.

**Comment by tkem** [comment]
@lmignon : I'd need to know more details about your use case to make any judgement about it, but I think your issue (and probably most arising from this change) can be solved by adding one level of indirection, e.g.:

```
def method(self, name):
    return _method(self, self.work, name)

@cachedmethod(operator.attrgetter('_cache'),
                  key=lambda work, name: keys.hashkey(
                      work.collection._name if work._collection is not None else None,
                      work.model_name, 
                      name)
def _method(self, work, name)
     ...
```

**Comment by lmignon** [comment]
Ok I see the problem. Nevertheless this change remove a useful functionality....
In our case we declare the cache at class level. (not on the instance). Therefore the cache is shared by all the instances. That means that each time a method is call for instances with some equal attributes  the cache will be used since the key is build from these attributes. But these attributes must not be part of the  method since these are already defined on self. If we add these parameters to the method signature, we modify the implementation just for the cache (IMO it's a bad practice)

Here it's a dummy sample code to illustrate my needs

```python

def MyClass(object):

    def __init__(self, name):
        self._name = name

    @cachedmethod(operator.attrgetter('_cache'), key=lambda self: keys.hashkey(self._name))
    def descr(self):
        return self._name.upper()

MyClass._cache = LRUCache()
```

**Comment by lmignon** [comment]
@tkem It the problem is the default key provided into the method signature this one could be solved in an other way...

```python
import functols

def cachedmethod(cache, key=None, lock=None):
    """Decorator to wrap a class or instance method with a memoizing
    callable that saves results in a cache.

    """
    def decorator(method):
        if lock is None:
            def wrapper(self, *args, **kwargs):
               if key:
                   # provide instance as first argument of the key method.
                    key =  functools.partial(key, self)
                else:
                     key=keys.hashkey
                c = cache(self)
                if c is None:
                    return method(self, *args, **kwargs)
                k = key(*args, **kwargs)
                try:
                    return c[k]
                except KeyError:
                    pass  # key not found
                v = method(self, *args, **kwargs)
                try:
                    c[k] = v
                except ValueError:
                    pass  # value too large
                return v
        else:
            def wrapper(self, *args, **kwargs):
               if key:
                   # provide instance as first argument of the key method.
                    key =  functools.partial(key, self)
                else:
                     key=keys.hashkey
                c = cache(self)
                if c is None:
                    return method(self, *args, **kwargs)
                k = key(*args, **kwargs)
                try:
                    with lock(self):
                        return c[k]
                except KeyError:
                    pass  # key not found
                v = method(self, *args, **kwargs)
                try:
                    with lock(self):
                        c[k] = v
                except ValueError:
                    pass  # value too large
                return v
        return _update_wrapper(wrapper, method)
    return decorator
```

**Comment by lmignon** [comment]
@tkem What do you think about my last comments?

**Comment by tkem** [comment]
Regarding your dummy example, there's no need to define a custom `key` function, anyway:
```
class MyClass(object):

    def __init__(self, name):
        self._name = name

    def descr(self):
        return self._descr(self._name)

    @cachedmethod(operator.attrgetter('_cache'))
    def _descr(self, name):
        print(name, 'descr called')
        return name.upper()

    _cache = LRUCache(maxsize=10)
```
Or, if - for whatever reason - you shy away from adding an extra non-public method:
```
class MyClass(object):

    def __init__(self, name):
        self._name = name

    def descr(self):
        @cached(self._cache)
        def _descr(name):
            return name.upper()
        return _descr(self._name)

    _cache = LRUCache(maxsize=10)
```
And don't forget that for non-trivial use cases you can always use the cache classes directly:
```
class MyClass(object):

    def __init__(self, name):
        self._name = name

    def descr(self):
        try:
            s = self._cache[self._name]
        except KeyError:
            s = self._cache[self._name] = self._name.upper()
        return s

    _cache = LRUCache(maxsize=10)
```
Case closed.

**Comment by lmignon** [comment]
@tkem Ok, you're the author and you decide but I remain convinced that it is a bad idea to have removed `self` from the list of arguments passed to the function specified by the key argument (except for the default one). Thank you for the alternatives to the initially supported approach.

**Comment by tkem** [comment]
@lmignon: Well, opinions may differ, and the ones expressed in this module are solely those of the author ;-)
Anyway, thanks for pointing out this use case, and having me think about it!
I think that at least the last two alternatives given by me are superior to your original implementation, since they don't require a `lambda` to get hold of the cache instance. However, I respect that your mileage may vary.
