### ISSUE TITLE
Add a cache_pop() method to compatible decorators

### ISSUE THREAD

**Issue by dmulter** [tkem/cachetools#108]
Please consider adding another method to all decorators called `cache_pop(*args, **kwargs)` that takes the same arguments as the wrapped function. This would enable a use case to clear a specific entry. This feature is not available in `functools.lru_cache` and would be a valuable extra feature in `cache tools`.

**Comment by tkem** [comment]
I get your point, but the `func` decorators are really just there as a migration aid (one way or the other). So I won't add any functionality there.
With the "native" `cached` and `cachedmethod` decorators, this should already be possible. Just pass in an "external" cache, and then do something like `del cache[key(*args, **kwargs)]`.

**Comment by dmulter** [comment]
Understood, feel free to close.

**Comment by tkem** [comment]
Thanks for your feedback, anyway!

**Comment by gitricko** [comment]
> I get your point, but the `func` decorators are really just there as a migration aid (one way or the other). So I won't add any functionality there.
> With the "native" `cached` and `cachedmethod` decorators, this should already be possible. Just pass in an "external" cache, and then do something like `del cache[key(*args, **kwargs)]`.

May i know how this should work. I tried the following.

```
    @cachedmethod(operator.attrgetter('cache'))
    def delete_cache_key(self, key):
        if self.cache.__contains__(key):
            del self.cache[key]
        else:
            LOG.debug("{} key not found".format(self.node_index))
```

TTLCache is created on the module level
eg:
```
CACHE = TTLCache(
                maxsize=os.getenv('INFER_NODE_CACHE_MAXSIZE',10),
                ttl=os.getenv('INFER_NODE_CACHE_TTL',600)
            )
```

It is pass to the class like this:

```
    def __init__(self):
        self.cache = CACHE
```

The TTLCache works as it suppose to in my cachemethod

```
    @cachedmethod(operator.attrgetter('cache'))
    def getCachedRecommender(self, tenant_uuid):
        LOG.debug("Node #{}: Caching Model for tenant_id: {}. Current cache length: {}".format(self.node_index, tenant_uuid, len(self.cache)))

        # get models from Storage
        model_zip_file = self.storage.get_model(tenant_uuid=tenant_uuid)
       ...
        return r
```

However, when i try to delete a cache via key.. it seems that it was successful but never deleted unless it is expired.

**Comment by gitricko** [comment]
ok, i will answer my questions. i need to do this for deletion.

```
def delete_cache_key(self, key):
        key2 = cachetools.keys.hashkey(key)
        if self.cache.__contains__(key2):
            del self.cache[key]
        else:
            LOG.debug("{} key not found".format(self.node_index))
```
