### ISSUE TITLE
Add more cache implementations/caching strategies

### ISSUE THREAD

**Issue by tkem** [tkem/cachetools#114]
See https://en.wikipedia.org/wiki/Cache_replacement_policies (be aware of patent issues, though).

**Comment by tkem** [comment]
Anyone volunteering for Bélády's algorithm?

**Comment by kashif-nineleaps** [comment]
Hi @tkem , I am not sure about Bélády's algorithm, I mean what policy shall I use to discard the data since I don't know in advance whether it will be used or not. Is it okay if I start with a simple algorithm for now like MRU and then I can take a look at more advanced ones ?

**Comment by mohdkashif93** [comment]
Hi @tkem , I am not sure about Bélády's algorithm, I mean the part where how will we decide if a particular data is to be discarded or not, since we don't know in advance about whether it will be used in future or not. Is it okay, if I take a look at more simpler techniques like MRU and once that is done, I can move towards the advanced ones.

**Comment by tkem** [comment]
@mohdkashif93: When I mentioned Bélády's algorithm, I was mainly joking (or trying to raise attention) ;-)

Please feel free to tackle any algorithm you see fit. Before submitting a PR, however, please make sure that
- it adds actual value compared to the caching algorithms already present in the library
- you provide reasonable unit test coverage (I won't let that bar drop beyond 100% any more)
- flake8 keeps shut up, and you generally follow "good coding style"
- you're prepared for a thorough and possibly frustrating code review process
Then we'll talk ;-)

**Comment by mohdkashif93** [comment]
@tkem lol, I can't believe I was so stupid to not understand the joke ;-) Great, I will follow your guidelines and for now I will start with understanding the code and will ping you up in case I have any doubts :)

**Comment by impredicative** [comment]
Maybe see if this makes sense:

https://techxplore.com/news/2019-04-data-compression-technique-faster.html
https://people.csail.mit.edu/poantsai/papers/2019.zippads.asplos.pdf

**Comment by tkem** [comment]
Due to time and resource constraints, no more cache implementations will be added for now (unless they are really, _really_ cool, of course). See #222 for more information.
