### ISSUE TITLE
Documenting the _Link class used in TTLCache

### ISSUE THREAD

**Issue by haiyanghe** [tkem/cachetools#116]
Hi, would it be possible if there could be some documentation regarding the usage of the `_Link` class in TTLCache? The code is a bit convoluted to read due to the `__link` attribute referring to something different.

Will be happy to make a PR from suggestions.

**Comment by tkem** [comment]
What do you mean by 
> due to the __link attribute referring to something different.
???

**Comment by haiyanghe** [comment]
Sorry, I made a typo, I meant that the `__links` attribute refers to a `OrderedDict` keyed by hash rather than a list of `_Link` objects. Could there be some docs with some rationale on `_Link`?

**Comment by tkem** [comment]
It's an `OrderedDict` which maps cache keys to `_Link` objects, so IMHO the name is appropriate.
Otherwise, it's an implementation detail of `TTLCache` and probably subject to change, so I don't see much need for additional docs. I also wouldn't know what to write, since I think it's pretty obvious what it does...

**Comment by haiyanghe** [comment]
I can try to add some docs to it, would you be ok with taking a look at it?

**Comment by tkem** [comment]
I'll have a look at it, but I won't make any promises...

**Comment by tkem** [comment]
Or even better, get rid of the `_Link` class alltogether. It's basically a remnant of the initial implementation, before LRU and TTL were switched to use `OrderedDict` for #64. 
I was thinking about doing this myself when preparing for v3.0, but somehow ran out of time...

**Comment by tkem** [comment]
Well, spare yourself the trouble and have a look at https://github.com/tkem/cachetools/tree/refactor/ttl
I managed to dig up my efforts replacing the `_Link` class with another `OrderedDict`... still don't know if it's worth the effort and would need much more testing and timing.
Regarding any "confusion": The initial implementation was pretty much a backport of Python 3's `@lru_cache` to Python 2.7 with `ttl` added. See https://github.com/python/cpython/blob/3.7/Lib/functools.py#L393 for the standard library code. I still think it's quite obvious and doesn't need any further documentation.

**Comment by haiyanghe** [comment]
I'm working on a similar implementation without `_Link` and using `OrderedDict` and I haven't bench-marked it. I have a feeling that the implementation similar to the one from the standard library will end up being more performant.
