### ISSUE TITLE
Consider time.monotonic if available

### ISSUE THREAD

**Issue by impredicative** [tkem/cachetools#123]
[`time.monotonic`](https://docs.python.org/3/library/time.html#time.monotonic) is said to be available system-wide since Python 3.5. Why not use it as a default for `cachetools.TTLCache` and `@cachetools.func.ttl_cache` if it's available? As the docs for it say, "*The clock is not affected by system clock updates*". Using `time.time` as the default could sometimes lead to bugs.

When the `cachetools` package is imported, it could perhaps do something like this:

```python
try:
    DEFAULT_TTL_TIMER = time.monotonic
except AttributeError:
    DEFAULT_TTL_TIMER = time.time
```

**Comment by tkem** [comment]
Good point, actually!

**Comment by impredicative** [comment]
Thanks. I look forward to a PyPI release for the same.
