### ISSUE TITLE
DeprecationWarning in pytest

### ISSUE THREAD

**Issue by WhiteHalmos** [tkem/cachetools#124]
https://github.com/tkem/cachetools/blob/90d35075eca92d2064bb87ddc1f19f0bf82311c9/cachetools/abc.py#L7

DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    class DefaultMapping(collections.MutableMapping):

-- Docs: https://docs.pytest.org/en/latest/warnings.html

**Comment by WhiteHalmos** [comment]
A workaround to ignore this is here: https://github.com/WhiteHalmos/emailer/commit/1fe08b15ef3f07bc305bb890223223ce400dabf5

**Comment by tkem** [comment]
Good point, actually!

**Comment by tkem** [comment]
See https://docs.python.org/3.7/library/collections.html:

> Changed in version 3.3: Moved Collections Abstract Base Classes to the collections.abc module. For backwards compatibility, they continue to be visible in this module through Python 3.7. Subsequently, they will be removed entirely.

**Comment by tkem** [comment]
Looks like `flake8` still has issues with Python 3.8, I'd like to defer this until those are fixed.
