### ISSUE TITLE
Split methods in TTLCache for simpler inheritance

### ISSUE THREAD

**Issue by Matityahul** [tkem/cachetools#125]
I want to be able to do the follow things **from a custom class that inherit from the TTLCache**:
* Detect whether a missing item is really missing or just expired
* Detect deletion by "expire" method
* Delete item without expiration validation

Of course we just need to split some methods in the TTLCache class and I already did it and added a pull-request for that.

**Comment by tkem** [comment]
So you basically want to add three "protected" methods to TTLCache that would all have to be documented, unit-tested, and maintained?
Sorry, but I don't consider your use case common enough to warrant the extra effort.
