### ISSUE TITLE
Compressed cache

### ISSUE THREAD

**Issue by impredicative** [tkem/cachetools#127]
Is it possible to have a compressed cache? To start with something simple, how can I use `functools.lru_cache` with `gzip.compress` plus `gzip.decompress` all together? For convenience, assume the input and outputs to the target function are `bytes`. Can this be done with a custom decorator, and what would such a decorator look like? I should then similarly be able to use this with one of the preexisting `cachetools` decorators.

I consider this request important to save on memory while affording a bit of CPU expense. The size of the `bytes` object that I cache can be 50K to 500K of text multiplied by the cache size, making it worthy of compression.

Next, for `cachetools`, would it make sense to allow an optional `key_compression` and `value_compression` argument for each of its caches? Sometimes I need just the value compressed. If the key is stored in-memory, sometimes I also need it compressed. This would take in as an argument say the module object `gzip` or `zlib`, etc., so long as the object has the `compress` and `decompress` callables. For this to work in theory, what assumptions about the cached objects would have to be made? Any object can be held in memory, but only `bytes` objects can be compressed.

Sometimes I don't need even a compressed version of a 500K key to be stored in memory in a dict. In such cases, just a SHA2 hash as a key will suffice.

**Comment by tkem** [comment]
I thinks this goes well beyond the scope of `cachetools`. You might be able to implement something based on cachetools, i.e. something (decorator?) that passes the already compressed data to `cachetools`, but no support for this is planned in `cachetools` itself.

**Comment by impredicative** [comment]
I would like this to be revisited. There is no other package on PyPI that I know of which implements compressed in-memory caching, making it all the more beneficial. Having it as a native feature in `cachetools` can be a game-changer for so many applications. Several of my applications which cache web pages as keys and/or values are wasting memory by not using compression.

If you insist that this shouldn't be a core part of cachetools, can we work on a class and a decorator which is used in conjunction with one of the cachetools classes and decorators? These proposed new classes and decorators can then be added to another new package which has cachetools as its requirement. I need help with this.

Technical details about this request are in my former comment. Thanks.
