### ISSUE TITLE
File-based caching

### ISSUE THREAD

**Issue by deeplook** [tkem/cachetools#128]
I've just stumbled over this package. Without looking deeply at the code I assume this is all memory-based caching, so I wonder if it would be easy to define subclasses which save larger amounts of cached data to files, too? Call it a level-2 cache, maybe? ;)

**Comment by tkem** [comment]
I thinks this goes well beyond the scope of `cachetools`. I vaguely remember some disk-based caching library that somehow used `cachetools` or at least implemented a similar interface, but I couldn't find it easily enough.

**Comment by impredicative** [comment]
@deeplook There are many disk-based caching packages. One such package is https://pypi.org/project/diskcache/ and it works well.

I think tkem is doing the right thing limiting the scope of `cachetools`. Many packages have become unmaintainable just because their scope grew too much.

**Comment by tkem** [comment]
@impredicative: You're absolutely right ;-)
The last couple of versions of `cachetools` were more concerned with _removing_ features that a younger, more light-hearted version of me added without thinking too much about the consequences (i.e. maintenance) ;-)
So, _adding_ anything that goes too much beyond the current scope is definitely not an option, and should preferably be handled outside this module.

**Comment by olirice** [comment]
There's a `@cached` compatible, SQLite based LRU cache with optional ttl available at [cachetools_ext](https://github.com/olirice/cachetools_ext) if anyone else ends up here

**Comment by thiswillbeyourgithub** [comment]
For anyone else wondering I can recommend [joblib's Memory](https://joblib.readthedocs.io/en/latest/auto_examples/memory_basic_usage.html)
