### ISSUE TITLE
Mention that default cachetools.keys.hashkey prevents pickling of cache

### ISSUE THREAD

**Issue by FlorianWilhelm** [tkem/cachetools#130]
I guess a common use-case of `cachetools` is also to store the cache for future usages. This will surely often be done with the help of the `pickle` module. A strange problem arises when the default `key=cachetools.keys.hashkey` parameter is used. Since this function produces a `_HashedTuple` with a hash depending on **runtime**!

To reproduce, execute the following script:
```python
import pickle
from cachetools.keys import hashkey

my_key = hashkey( ('abc', 1) )
print("Hash of original key", hash(my_key))
with open('my_key.pickle', 'bw') as fh:
    pickle.dump(my_key, fh)
```
then execute **afterwards** the script:
```python
import pickle
from cachetools.keys import hashkey

my_key = hashkey( ('abc', 1) )
with open('my_key.pickle', 'br') as fh:
    my_orig_key = pickle.load(fh)

print("Hash of original key", hash(my_orig_key))
print("Hash of key that perfectly recreates the original key", hash(my_key))
```
The output of those scripts, ran one after another, will be like:
```
Hash of original key 5309672140285697764

Hash of original key 5309672140285697764
Hash of key that perfectly recreates the original key -3981844488918652932
```
Although anyone would expect that `('abc', 1)` leads to the same hash, this it isn't the case. In practise, that means that you might load your cache but you will not actually use the content of it but rather create "duplicate" entries. 

A simple workaround is to just not use `cachetools.keys.hashkey` but this should be mentioned in the docs or one could change the default implementation to not using `_HashedTuple`. Is this used for performance reasons btw? From the implementation is seems that it avoids the recalculation of the hash.

**Comment by tkem** [comment]
Nice catch ;-)

You didn't say so, but I guess you're using a Python version >= 3.3, so what you see is a side effect of Python's _hash randomization_.

Please note, that
- I'm not a big fan of `pickle` and do not actively use it in production code; I think there are some basic flaws with it, which makes it usable only for small/demo projects, e.g. if a cache's implementation changes from `cachetools` version X to version Y, your pickled caches won't work as expected.
- the cachetools documentation doesn't mention `pickle` at all (for reasons stated above), so there's no guarantee it will work.
- yes, there are some basic unit tests regarding pickling caches by popular demand, but still I won't officially commit to support pickling and unpickling caches.

Still, your point seems to be valid regarding `hashkey`, but instead of documenting it I'd prefer if it was actually fixed. On first sight, it looks like adding the following to `_HashedTuple` does the job, at leas on Python 3.7.3:

```
    def __getstate__(self):
        return {}
```

Would be glad if you could confirm that this works for you, too.

**Comment by tkem** [comment]
BTW, `_HashedTuple` was inspired by the Python standard library `functools.lru_cache` implementation:
https://github.com/python/cpython/blob/3.7/Lib/functools.py#L411

**Comment by FlorianWilhelm** [comment]
@tkem Thanks for the really fast reply & solution! I really do appreciate this.

Regarding your points:
* I am also not a big fan of `pickle` but as you said for prototypes, it's really cool even having the downsides you mentioned. And let's be honest, in a production setting, I would use some fancy distributed caching system based on Redis or Celery or something else that takes at least two days to set up correctly rather than cachetools. My point is, cachetools is really awesome to do simple caching without too much hassle in prototypes and small apps and so does pickle. Thus, since they target both the same use-cases, they should work well together in my point of view. And btw, I only found cachetools because of some stackoverflow questions that referred me to it because they said it would support pickling the cache in contrast to `functools.lru_cache` ;-) 

* When I started to do OSS projects, I had to learn that having good documentation helps with avoiding unnecessary questions in issues and thus saves time eventually. My advice would be to actively mention how pickle works together with cachetools since your users do it anyway. Of course, also state your reservations against pickle but let the users decide if it applies to their use-case or not. 

* You are correct, I am using Python 3.6 and 3.7 (tested both) and didn't know about the cache randomization yet. So with your `__getstate__` solution, you are basically disabling this randomization for the object, I take it. Sounds like a good idea. In my use-case, I have only positional arguments but since you use `_kwmark = (object(),)` as a marker for keyword arguments, I guess this also needs some changes to deactivate the randomization, right?

* I added `__getstate__` to `_HashedTuple` and it worked in my application fine. Thank you! Bear in mind that my application only uses positional arguments, so I guess if keyword arguments are present, the bug is still there.

**Comment by FlorianWilhelm** [comment]
@tkem Fixing the problem for `_kwmark` was actually more difficult than expected but I got it sorted out. Everything works fine in Python 3 but fails under Python 2.7 thus I deactivated the new unittests for Python < 3. Python 2.7 has reached the end of life and putting more effort into supporting it makes no sense to me. Let me know what you think about the PR.
