### ISSUE TITLE
TTLCache - Extend TTL when that item has been access

### ISSUE THREAD

**Issue by gitricko** [tkem/cachetools#136]
Would it be useful if we can get ttl expire to be extended when the item is access... If alot of keys are added into TTLCache at the same time... it will expire at the same time... Causing alot of memory swap.

I think TTLCache would be more useful when it is expired after TTL elapse when it is not used. Of course, if max_size is reach... LRU will kick in.

What do you think ?

**Comment by tkem** [comment]
Frankly, I don't see a proper use case for that. What you describe sounds very much like the LRU strategy. TTL is used to give a "hard timeout" for cached items, so they will be refreshed after some time, no matter how frequently they are accessed. Think of the weather report example - the weather for NYC will probably not be updated for days ;-)

**Comment by gitricko** [comment]
Thanks for the reply. However, our use-case is unfortunately now weather for NYC. What i want is not to have TTL kick in at the same time as creating of the cache with TTL set is done during container boot time... Then that means all my cache will expire at the same time. Having an option to extend the TTL from the last use time is useful in this case. 

Of course, i can use LRU without TTL... i like to use TTL as the safety net where by i do not need to caculate my capacity of my cache amount for each container at run time. Having TTL, give the container less likely to crash due to insufficient memory. As unused keys will be unloaded after a while when not use. 

Hope this make sense of our use-case as compare to weather usecase

**Comment by tkem** [comment]
So, if I understand correctly, you don't want to use TTL to limit the time a cached item is available, but so you don't have to set a maximum size, and you *hope* that most cache items will expire due to inactivity before you run out of memory?

Sorry, but I don't consider this a valid use case, it sounds more like a really stupid idea!

**Comment by gitricko** [comment]
Probably from your point of view...  Because the cache is created at the same time during loading... all of them will be invalidated at the same time causing lots of reloading from disk. I don't think that is stupid. 

Nevertheless, if you are unwilling to suggest a way forward... no need to label idea stupid or clever. I can still manage to change the enhance the code myself. Nevertheless, you have create a very elegant API.

Thanks for your feedback

**Comment by tkem** [comment]
Sorry, didn't mean to sound rude - I didn't understand that your cache is pre-filled at startup. My bad.
Still, what speaks against LRU strategy for this? If all cached items are available, you know the number of cached items and can create an LRU cache the same size (or x2, x3, whatever), don't you? So, what good is the TTL?

**Comment by gitricko** [comment]
no problem.

Our pre-calculation of calculation is one way... however, the problem is that we are caching objects that have irregular size... couple this with each instance of the cached may have uneven distribution of keys due to our hashing algorithm... this make the calculation abit more difficult (but of course not impossible eg: by being very conservative)

Having TTL to able to timeout and flush out unused cache free up memory in our containers... and we can be more aggressive in scoping memory for each containers. (being cheap here) This is a fine grain optimization for us to save alittle cost

**Comment by tkem** [comment]
For irregular sized objects, have you tried using a `getsizeof` function?

**Comment by STofone** [comment]
easy by another cache lib
https://github.com/Yiling-J/theine/issues/25
