### ISSUE TITLE
Timed (since last touched) LRU cache

### ISSUE THREAD

**Issue by kosh-b** [tkem/cachetools#139]
Hi, im looking for a cache implementation for a Timed based LRU cache, in which the Time based refer to ttl *BUT* since the last touch and not from the first time an object was added to the cache (Ofc this should work with the current 'maxsize' limitation)

You had any thoughts about this? i think it might be useful for long living caches.

I want to use cachetools and thought about patching TTLCache.__getitem__ (after successfully querying an item, extending its link.expire with the current time + ttl),
[Im not sure its going to work due to the __iter__ function),
What do you say?

Ill be glad to do so with change that will survive any changes in TTLCache functions, which means maybe creating a function similar to on_item_touch() that may be overridden.
Or just to hear any better ideas about how to do that,
Thank you :)

**Comment by tkem** [comment]
Please see #136. I'm still skeptical about this being a valid use case - what's the advantage compared to using plain `LRUCache`?

**Comment by kosh-b** [comment]
Lets call what i have described A TimeBasedLRU:
LRU cache + with time to live for each element that "updates" (or re-insert them same value to the structure) when this item is touched.

1) len(TimeBasedLRU) <= len(LRU) (so that less use of memory that we dont need.
2) In situation when im storing some items in the cache which relevant for a user (but just for a short time), lets say i have a drop down list and the value of this list is different for every user.
while my user is "online" i want to save this list, when he is not "online" anymore i can give up on this memory.
the "online" definition is: X seconds since his last action.

This is simplification of the main usage of this cache - TimeBasedLRU,
In this case, in each touch (or any other logic) we can remove the old "drop down lists" for the offline users, why would i wait that my cache will be full until ill remove them? that will be a waste of memory.

I think that explains (shortly) the need of this cache

**Comment by kosh-b** [comment]
@tkem What do you say about this flow?
If still you dont think this deserve an implementation, How would you suggest to implement that based on cachetools?

**Comment by tkem** [comment]
I'd suggest to use a simple LRUCache for scenarios like that. Your system will have to be able to deal with a full cache anyway, so I see little benefit in expiring items early just to free some memory.

**Comment by adamsmith-sfdc** [comment]
One use case where freeing extra memory is important (but keeping recently used items is equally important) is if you are managing a separate cache for each node in an auto-scaling pool that uses memory utilization as its scaling metric and uses a consistent hash method to store/fetch objects in a subset of nodes. e.g. N nodes each with their own cache, objects are distributed with replication across M nodes (M < N) at any given time. As node pool size increases/decreases, objects will be re-associated with different nodes in the pool.

If your auto-scaling is configured to target, say, 60% average memory utilization per node, but set your cache maxsize to allow for up to 80% memory utilization, your pool will scale when more items are added bringing your utilization above 60% on average. But as more nodes are added to the pool, items aren't necessarily evicted from the caches and each node will remain at 80% and more nodes will continue to be added to the pool.

Strictly using a TTLCache in this situation would fix the issue with infinite scaling, but you would often be evicting items that are actively being used which could be expensive to re-add.

@tkem I see you're not accepting feature requests anymore so I won't open a new ticket, but I wanted to provide another scenario that's maybe more justified where this sort of cache behavior would be useful.
