### ISSUE TITLE
Drop Python 2.7 support

### ISSUE THREAD

**Issue by tkem** [tkem/cachetools#143]
Python 2 will reach end of life on Jan 1 2020. Although `cachetools` doesn't include much code for backward-compatibility, some small things may be cleaned up by dropping Python 2 support, e.g. setting `__wrapped__` on decorated functions explicitly.

**Comment by tkem** [comment]
Note that for v4.0, Python 3.4 support should probably be dropped, also:
https://devguide.python.org/#status-of-python-branches

**Comment by hugovk** [comment]
Please see PR #144.

**Comment by tkem** [comment]
Already done in v4.0.0 branch.
