### ISSUE TITLE
How to do ttl_cache + custom key ?

### ISSUE THREAD

**Issue by wimglenn** [tkem/cachetools#146]
Thanks for your work on this clean and cool library!

I like being able to specify the hash key with 

    @cached(cache, key=mykey)

I also like the [`cachetool.func`](https://cachetools.readthedocs.io/en/latest/#module-cachetools.func) conveniences such as 

    @ttl_cache(maxsize=512, ttl=60*5)

Could you add a bit more feature parity in these interfaces? E.g. a way to specify the hashkey for `@ttl_cache` and/or a way to specify a ttl for `@cached`.  Cheers.

**Comment by tkem** [comment]
The `cachetools.func` decorators are there to mimic the standard library `functools.lru_cache`, mostly to provide some sort of migration path. So no, sorry, you're limited to `typed=True` or `typed=False` regarding choice of hash key, to keep it simple.

**Comment by wimglenn** [comment]
OK, no problem. It ends up being pretty clean anyway with the existing APIs:

```
from cachetools import cached 
from cachetools.ttl import TTLCache   
cache = TTLCache(maxsize=512, ttl=60*5)   

@cached(cache, key=mykey)
def myfunc(...):
    ...
```
