### ISSUE TITLE
[Question] TTLCache - override expire

### ISSUE THREAD

**Issue by sidps** [tkem/cachetools#148]
I need to subclass TTLCache to override insertion and deletion semantics. I could do this by overriding it's `__setitem__` and `__delitem__` for basic insertion and deletion. However, I'd also like `__delitem__` to apply to expired items on calls to expire. How do I achieve this?

**Comment by tkem** [comment]
Apart from the examples given in https://cachetools.readthedocs.io/en/latest/#extending-cache-classes, cache classes are not really meant to be extended or their behavior overridden. So your best bet would probably be to roll your own.
