### ISSUE TITLE
TTLCache get function should check for expiration

### ISSUE THREAD

**Issue by Sytten** [tkem/cachetools#149]
It seems weird to me that `cache[key]` checks for expiration, but not `cache.get(key)`. though this is a breaking change, so I understand if you don't want to change it.

**Comment by tkem** [comment]
What makes you think, ``cache.get(key)`` does not check for expiration?

**Comment by Sytten** [comment]
If I understand correctly this is the method that is called:
https://github.com/tkem/cachetools/blob/master/cachetools/ttl.py#L185
It basically forwards the call the to parent cache which doesn't have any sense of TTL
Compared to the dunder https://github.com/tkem/cachetools/blob/master/cachetools/ttl.py#L80
We can clearly see the check for expiration.

**Comment by tkem** [comment]
Well, have you actually tried it out?

**Comment by vlcinsky** [comment]
I confirm, TTL cache expires properly.

```python
import time

import cachetools.func

CACHE_TTL = 5
MIN_EXPENSIVE_DURATION = 3


@cachetools.func.ttl_cache(ttl=CACHE_TTL)
def cached_func(name: str):
    time.sleep(MIN_EXPENSIVE_DURATION)
    print(f"now: {time.time()}")
    return f"||{name}:{name}||"


def measure_duration(func, arg, expected_res):
    start_time = time.time()
    res = func(arg)
    end_time = time.time()
    assert res == expected_res
    return end_time - start_time


def test_while():
    arg = "alpha"
    expected_res = "||alpha:alpha||"

    # try the first time, this time as expensive call
    assert measure_duration(cached_func, arg, expected_res) >= MIN_EXPENSIVE_DURATION

    i = 0
    # try another times until we miss the chache
    while measure_duration(cached_func, arg, expected_res) < MIN_EXPENSIVE_DURATION:
        assert i < CACHE_TTL
        i += 1
        time.sleep(1)
    assert i == CACHE_TTL
```

What confused me for a moment is the fact, the expiration is not measured from the moment you start the call to the cached function, but from the moment the cached function returns.

Existing implementation and behaviour seems correct to me.
