### ISSUE TITLE
Memory-aware LRU caching

### ISSUE THREAD

**Issue by miso-belica** [tkem/cachetools#152]
I am searching for the LRU/LFU cache in Python which counts with the free memory. I found this SO question https://stackoverflow.com/questions/23477284/memory-aware-lru-caching-in-python and wonder if you can consider implementing and adding something like this into this library.

My use-case is to save as many objects as I can in memory and when the free memory starts to be a problem then remove the oldest or the least used objects when adding a new one. I can't really predict the size the same way as it is in the SO question.

What do you think? Thanks in advance and have a nice day :)

**Comment by tkem** [comment]
Probably not. Have you tried using `WeakValueDictionary` from the [weakref](https://docs.python.org/3/library/weakref.html) module? Should work with the `cached` decorator.

**Comment by miso-belica** [comment]
@tkem Thanks for the response. I checked the `weakref` module and weak dictionaries before but I don't think it's what I suggest here. There is written this:

> `WeakValueDictionary`: Mapping class that references values weakly. Entries in the dictionary will be discarded **when no strong reference to the value exists** anymore.

But I want to hold the values even if they are not referenced elsewhere. I want to start throwing them away only after RAM is increasing to its limit.

If you still think the module can be helpful, can you be more specific how? Maybe even a little pseudocode?

**Comment by tkem** [comment]
> A primary use for weak references is to implement caches or mappings holding large objects, where it’s desired that a large object not be kept alive solely because it appears in a cache or mapping.

It's quite a while since I used any of this, but AFAICR values were not discarded instantly when all other references went away. 

> However, until the object is actually destroyed the weak reference may return the object even if there are no strong references to it.

So this is basically left to the garbage collector. Might work for you, might not. However, using `psutil` or something similar is definitely beyond the scope of this module.
