### ISSUE TITLE
Cache type proposal

### ISSUE THREAD

**Issue by salimaboubacar** [tkem/cachetools#153]
Hello ! I have a cache idea with interesting use cases I think. I'm opening this issue to know if you would be interested in a PR with this kind of cache or if I should keep it in my app because you think this is too specific.

It's basically a "cache with fallback", with 2 caches internally, a TTL and a LRU.
- When there is no value in the TTL cache, you call the underlying function.
   - If the call returns a value, you save it in both caches.
   - If the call raises an error, you save in the TTL cache that you had an error
- If you have a value in the TTL cache, you return it
- If you have an error saved in the TTL cache, you return the value from the LRU cache if it exists, otherwise you raise the error

This behavior has notable properties :
- Your code will never call the underlying function more frequently than the ttl of the TTLCache
- If the underlying function returned a value once, you are guaranted to read at least that value (or a more recent one) in any call in the future
=> It's like a LRU cache with a "try to refresh if possible" if the value you want to read is too old
=> It's like a TTL cache with "fallback to last value" even if you cache miss because the last successful run of the underlying function is too old (and recent runs raised an error)

**Comment by tkem** [comment]
@salimaboubacar: Thanks for your input, but this really sounds a little too involved to get included, at least for now...
However, it looks like a nice strategy for handling transient errors, and I like how you combine two caches for this!
