### ISSUE TITLE
Unable to install version 4.0.0

### ISSUE THREAD

**Issue by xangxiong** [tkem/cachetools#154]
When installing cachetools version 4.0.0 through pip, it is failing with the error below.  OS is Ubuntu 16.04, Python 2.7.12, Pip 8.1.1

pip install cachetools==4.0.0
Collecting cachetools==4.0.0
Installing collected packages: cachetools
  Found existing installation: cachetools 3.1.1
    Uninstalling cachetools-3.1.1:
      Successfully uninstalled cachetools-3.1.1
  Rolling back uninstall of cachetools
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 335, in run
    prefix=options.prefix_path,
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 732, in install
    **kwargs
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 837, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 1039, in move_wheel_files
    isolated=self.isolated,
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 346, in move_wheel_files
    assert info_dir, "%s .dist-info directory not found" % req
AssertionError: cachetools==4.0.0 .dist-info directory not found
You are using pip version 8.1.1, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by xangxiong** [comment]
Seems to install fine with Python 3.5.2 and Pip 8.1.1.  Is Python 2.7.x going out of support for this library?

**Comment by igsu** [comment]
In addition to the above:

```
Collecting cachetools
  Downloading https://files.pythonhosted.org/packages/ff/e9/879bc23137b5c19f93c2133a6063874b83c8e1912ff1467a3d4331598921/cachetools-4.0.0.tar.gz 
  Running setup.py (path:/tmp/pip-build-YFmMXK/cachetools/setup.py) egg_info for package cachetools produced metadata for project name unknown. Fix your #egg=cachetools fragments.

Building wheels for collected packages: unknown
  Running setup.py bdist_wheel for unknown: started 
  Running setup.py bdist_wheel for unknown: finished with status 'error' 
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-HTkqoL/unknown/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpcmtMWypip-wheel- --python-tag cp27: 
  Traceback (most recent call last): 
    File "<string>", line 1, in <module> 
  IOError: [Errno 2] No such file or directory: '/tmp/pip-build-HTkqoL/unknown/setup.py' 
   
  ---------------------------------------- 
  Failed building wheel for unknown 
  Running setup.py clean for unknown 
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-HTkqoL/unknown/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" clean --all: 
  Traceback (most recent call last): 
    File "<string>", line 1, in <module> 
  IOError: [Errno 2] No such file or directory: '/tmp/pip-build-HTkqoL/unknown/setup.py' 
   
  ---------------------------------------- 
  Failed cleaning build dir for unknown 
Failed to build unknown 
```

**Comment by tkem** [comment]
As the [change log](https://github.com/tkem/cachetools/blob/master/CHANGELOG.rst#v400-2019-12-15) states, `cachetools` v4 requires at least Python 3.5.
With Python 2.7 reaching EOL in a few days, it was time to cut off some old braids.
Older versions are still available from PyPI, of course.
