### ISSUE TITLE
cachedmethod should optionally respect the state

### ISSUE THREAD

**Issue by c-thiel** [tkem/cachetools#159]
First of all thanks for this awesome package. I am using it alot lately!

**The Issue:**
Consider the following example:
```python
class Number:
    def __init__(self, number):
        self.cache = LRUCache(maxsize=5)
        self.number = number

    @cachedmethod(lambda self: self.cache, key=partial(hashkey, 'add'))
    def add(self, x):
        return self.number + x

    @cachedmethod(lambda self: self.cache, key=partial(hashkey, 'substract'))
    def substract(self, x):
        return self.number - x

number = Number(0)
print(number.add(5))  # = 5
number.number = 5
print(number.add(5))  # = Still 5, should be 10!
```
The second print shows 5 instead of the correct value 10, as the calculated key in the cache does not include any state from the class.

https://github.com/tkem/cachetools/blob/fa9d4760dc44cd77f5eafd30cbaeed40a3435c96/cachetools/decorators.py#L58

I argue that this behaviour is unexpected. All methods or properties for which this decorator is meant are based in some way on the state of the class (otherwise they would be classmethods or staticmethods). Thus the decorator should at least offer some simple way to include some attributes of the instance into the hashkey. Currently, correct me if I am wrong, another wrapper is required to achieve this.

**Solution**
I am not sure how a perfect solution should look like. Here are some proposals:

1. Pass self to the key function provided by the user. (Change the code snippet above to `key(self, *args, **kwargs) `. This however only makes sense if the default key is changed to `key=lambda x: keys.hashkey(x[1:])`, so that per default self is not incorporated. If we would incorporate self as default, that would include the cache so that basically no caching is performed. Still this would offer the user the possibility to provide a custom key function which accesses the state.
2. Introduce a new argument (such as `include_state`) which changes the key generation to `key(self, *args, **kwargs) `
3. Leave it to the user: Every __setattr__ should clear the corresponding cache entries.

Another option would be to introduce a completly new interface. Personaly i am using a wrapper around your decorator which looks like this:
```python
def cachedmethod(method_name, attributes=None, lock=None):
    """Decorator to cache a method, classmethod or property

    Parameters
    ----------
    method_name : str
        A unique identifier for the method. The method_name is incorporated in the cache-key
        so that the same cache can be used for multiple methods.
    attributes : list of str
        List of attributes of the calling instance to be additionally included into the
        cache-key. This is relevant if the output of the method is dependant on some
        instance states stored in attributes.
    lock : callable
    """
    assert attributes is None or type(attributes) is list, \
        'The attributes argument in the cachedmethod decorator must be a list of str or None.'
    attributes = [] if attributes is None else attributes

    def decorator(method):
        @wraps(method)
        def wrapper(self, *args, **kwargs):
            key = partial(hashkey, method_name, *[getattr(self, a) for a in attributes])
            caching = cachetools.cachedmethod(cache=operator.attrgetter('cache'),
                                              key=key,
                                              lock=lock)
            return caching(method)(self, *args, **kwargs)
        return wrapper
    return decorator
```
The cache could of course also be an argument. I am aware that this is by far not as flexible as your aproach. I also believe that I would have never written this decorator if there was a way to include the state into your decorator easily, but it does make the default usecase much shorter.

Let me know what you think about this! 
Thanks!

**Comment by tkem** [comment]
@c-thiel: Sorry for the late response - "real life" issues got in the way, somehow...

`self` was actually part of the key function arguments until v3.0.0, see also #107. I considered this a bug/oversight, but to my surprise, this was used as an undocumented "feature" by quite a few.

In retrospect, I should probably have considered your solution #1 (pass `self` to key, but ignore it in the default key function). I'll have to think about it again, but adding a second variant of the decorator or an optional flag or key function parameter sounds feasible.
