### ISSUE TITLE
Add type hints

### ISSUE THREAD

**Issue by and-semakin** [tkem/cachetools#160]
Thanks for the very useful library!

Since the library no longer supports Python 2 and only supports Python 3.5+, it would be useful to add type annotations to functions and methods. This library is not so big, so it should not be difficult.

Code that uses the library will benefit from this change because type checking tools will better understand it.

See:
* https://www.python.org/dev/peps/pep-0484/
* https://www.python.org/dev/peps/pep-0561/
* http://mypy-lang.org

If you are positive about this idea, then I can create a PR.

**Comment by Feijo** [comment]
I believe you could go ahead with the PR

**Comment by tkem** [comment]
@and-semakin: Sorry for the delay, shame on me... Thanks for your suggestion, but _currently_ I have no interest in maintaining type annotations in-tree. However, [typeshed](https://github.com/python/typeshed) may be a good place to contribute type annotations, if you are still inclined to do that...

**Comment by r-barnes** [comment]
I just spent some time trying to figure out what kinds of arguments `TTLCache` takes and thought I'd open a PR to add appropriate type annotations so this would be unambiguous. I found this while searching to see if there was an effort in progress.

Is your stance on not wanting type annotations still the same? If not, I can open a PR.

**Comment by tkem** [comment]
@r-barnes please see #183. Type hints were already submitted to typeshed, do I that's where you should start if you'd like to contribute.
