### ISSUE TITLE
Uncached methods

### ISSUE THREAD

**Issue by Fizzadar** [tkem/cachetools#165]
It could be very useful to have a uncached function variant, ie `cached_func.uncached()`. to bypass the cache in some cases. There's `__wrapped__` already but it's messy. Thoughts? Happy to PR.

**Comment by tkem** [comment]
Could you elaborate what you consider "messy" about `__wrapped__`?
I have no plans to support other means of accessing the original function, especially since `__wrapped__` is standard.

**Comment by Fizzadar** [comment]
I've no issue with `__wrapped__` itself but from an API/convenience perspective IMO a uncached method would be useful to have. I find `cached_func.uncached()` is more readable than `cached_func.__wrapped__()`.

**Comment by tkem** [comment]
@Fizzadar: You do have a point with readability, but `__wrapped__` is what's used by [lru_cache](https://docs.python.org/3/library/functools.html?highlight=lru_cache#functools.lru_cache), so I prefer to stick with that.
