### ISSUE TITLE
getsizeof ignores key size

### ISSUE THREAD

**Issue by impredicative** [tkem/cachetools#169]
According to the [docs](https://cachetools.readthedocs.io/en/stable/):

> Cache also features a getsizeof() method, which returns the size of a given value. The default implementation of getsizeof() returns 1 irrespective of its argument, making the cache’s size equal to the number of its items, or len(cache). For convenience, all cache classes accept an optional named constructor parameter getsizeof, which may specify a function of one argument used to retrieve the size of an item’s value.

This is a misleading indication of the cache's size, as keys can sometimes be really big too. It seems to ignore the key's size altogether. For a correct calculation, `getsizeof` should take an **item**, i.e. `(key, value)`, and return its size.

Perhaps the code can be updated to accept both `getsizeof(value)` and `getsizeof(value, key)`. This then shouldn't break anything.

**Comment by tkem** [comment]
@impredicative: Sorry for the delay. You're basically right of course, and I also considered using item size in the beginning. However, AFAIK, `getsizeof()` is used by a minority of clients, and most real-world examples I've seen use keys that are approximately equal size and at least an order of magnitude smaller than corresponding values. URIs and downloaded content in cached network requests are probably the most prominent example. Accepting one or two parameters in `getsizeof()` sounds feasible, though, but currently I think this is not a popular use case. I'll leave the issue open for future reference, however.

**Comment by tkem** [comment]
Another issue with item size is that cache implementations store `key` multiple times. `Cache` itself uses a separate size `dict` when `getsizeof()` is used, `LRUCache` uses an extra `OrderedDict` for remembering insertion order, etc.
So the `key` size would have to be counted multiple times, depending on the actual cache implementation.
Therefore, it's probably best to leave things as they are, maybe stating in the docs that `getsizeof()` only works if expected if keys are significantly smaller than item values.

**Comment by tkem** [comment]
There are also no examples of using `getsizeof()` in the documentation, so it should be added e.g. to the one decorating `get_pep(num)`:
```
# 640K should be enough for anyone
cache = LRUCache(maxsize=640*1024, getsizeof=len)
```
