### ISSUE TITLE
[Feature] Would it be possible to add a file save for the cashe

### ISSUE THREAD

**Issue by Zackaryia** [tkem/cachetools#175]
Adding the ability to save the cashe to be used between file runs would help with reducing function runs even when a file crashes.

**Comment by tkem** [comment]
Although it's not "officially" supported, it is possible to [pickle](https://docs.python.org/3/library/pickle.html) cache instances.
Beware, though, that, a cache's implementation may change, so it may not be possible to unpickle a cache that was pickled with an older `cachetools` version.
