### ISSUE TITLE
Don't use double underscores to simplify subclassing

### ISSUE THREAD

**Issue by dargueta** [tkem/cachetools#179]
I'd like to create an MRU cache (see #114) and the simplest way to do this would be to inherit `LRUCache` and change `__update` to:

```py
def __update(self, key):
    self.__order.setdefault(key, None)
    self.__order.move_to_end(key, last=False)
```

The problem is, anything with a double underscore is private to the class due to [name mangling](https://docs.python.org/3/tutorial/classes.html#private-variables). Thus, my subclass' `self.__order` is *not* the same as the superclass' one. I have to reimplement the entire thing from scratch, resulting in a lot of copy-pasted code.

An easy way to solve this problem would be to change all class-private identifiers (`__order`, `__update`, etc.) to use single underscores. This way, they still remain private (ish) to the class but still allow access to the subclasses.

**Comment by tkem** [comment]
The double underscores are there for a good purpose: To discourage use in derived classes. These are undocumented implementation details, and they may change or be dropped altogether in future versions due to refactoring. Even when subclassing, you should only use the documented interface of a class and not rely on implementation details.

**Comment by dargueta** [comment]
Well my intent was to contribute this so it'd be part of the library (and thus would be part of any refactoring) but I understand your point.

**Comment by tkem** [comment]
@dargueta: Thanks for your interest - no offense meant ;-)
The Web's full of discussions of "interface inheritance" vs. "implementation inheritance", so I didn't want to reiterate here...
I just think plain `Cache` serves as a reasonably good base class for any future cache implementations. If there is demand for further intermediate base classes, e.g. some `OrderedDictBasedCache`, that would be a good candidate for refactoring. But just adding an `MRUCache` probably wouldn't warrant this, IMHO.
