### ISSUE TITLE
Add optional Cython support?

### ISSUE THREAD

**Issue by dargueta** [tkem/cachetools#180]
After doing some testing it looks like using Cython at installation time can get significant performance savings without any code changes:

* LRU: 34% faster
* LFU: 6% faster <b>*</b>
* RR: 20% faster
* TTL
  * 0.25s: 41% faster
  * 1s: 41% faster
  * default: 39% faster

<sub>* LFU boost is far smaller because `collections.Counter` is part of the standard library and is thus ignored by Cython.</sub>

I tested using cProfile, with small variations of the following code:

```py
import cachetools.func
import random

@cachetools.func.lru_cache(512)
def my_function(a, b):
    return a % b

for _ in range(1000000):
    my_function(random.randrange(100), random.randrange(1, 100))
```

Doing this isn't that hard and can be made to be opt-in, so existing users wouldn't be impacted at all. Not even installation speed would change for them.

Cython would be even more effective if we had PEP 484 type annotations it could use for guidance. I've seen in #160 that typing support was declined but maybe this would be a bit more of an incentive?

**Comment by tkem** [comment]
See #182.
