### ISSUE TITLE
What are the units of maxsize argument?

### ISSUE THREAD

**Issue by neilpanchal** [tkem/cachetools#191]
I've tried searching the docs, source code, and pretty much everywhere on Google.

What are the units of `maxsize` argument in this library? Is it bytes? or kilobytes? bits?

After some experimentation, I found that the units of `ttl` is in seconds. I think this needs to be documented atleast in one of the following places: source code doc strings or the README.

My guess is it is in `bytes` since that's sort of the default. Also, I found a call to `sys.getsizeof()` which returns the size in bytes.

![image](https://user-images.githubusercontent.com/8161031/94335432-8336c680-ff90-11ea-80ad-e85fb31c4a90.png)

Again, this needs to be documented. After confirming, I can do a PR to the docs or the source code.

**Comment by tkem** [comment]
> Cache also features a getsizeof() method, which returns the size of a given value. The default implementation of getsizeof() returns 1 irrespective of its argument, making the cache’s size equal to the number of its items, or len(cache). For convenience, all cache classes accept an optional named constructor parameter getsizeof, which may specify a function of one argument used to retrieve the size of an item’s value.
https://cachetools.readthedocs.io/en/stable/#cache-implementations

> By default, the time-to-live is specified in seconds and time.monotonic() is used to retrieve the current time. A custom timer function can be supplied if needed.
https://cachetools.readthedocs.io/en/stable/#cachetools.TTLCache
