### ISSUE TITLE
Include a keybuilder for hashing of function arguments

### ISSUE THREAD

**Issue by veerte** [tkem/cachetools#198]
I faced a scenario where using the string representation of inputs was simply unacceptable, and had to copy the hashing keybuilder from cachetools. I think it would be a great idea to include it as aiocache.key_builders.hash_function_call so that it is readily available for people to use. Let me know if this feature would be desirable, and I'll get to work on a PR

**Comment by tkem** [comment]
Sorry, I don't know about aiocache - wrong repository?

**Comment by veerte** [comment]
Hahah that's right. Sorry, my mistake. Nice key builder btw, I think I'll borrow it.
