### ISSUE TITLE
Pycharm: cannot find reference 'keys' in module __init__.pyi

### ISSUE THREAD

**Issue by Xiaoven** [tkem/cachetools#199]
**OS:** MacOS, Catalina

**Pycharm version:** Pycharm professional 2020.3

**cachetools version:** 4.2.0

Screenshot

<img width="750" alt="Screen Shot 2021-01-02 at 23 49 08" src="https://user-images.githubusercontent.com/55338943/103461003-e8e7db00-4d55-11eb-9171-171bc6aa4023.png">

According to [this answer](https://stackoverflow.com/a/34514435/14246844), it is a good practice that Pycharm recommends. 

> The import statement uses the following convention: if a package’s __init__.py code defines a list named __all__, it is taken to be the list of module names that should be imported when from package import * is encountered. It is up to the package author to keep this list up-to-date when a new version of the package is released. Package authors may also decide not to support it, if they don’t see a use for importing * from their package.

Would you mind solving this problem?

**Comment by Xiaoven** [comment]
I find a workaround.

```python
import cachetools

@cached(cache=_cache, key=lambda simple_name, local_search=None: cachetools.keys.hashkey(simple_name))
def decide_priority(simple_name: str, local_search=None):
    pass
```

**Comment by tkem** [comment]
@Xiaoven: Frankly, this looks more like a Pycharm issue to me.
```
from cachetools.keys import hashkey
```
works fine on Python 3.8.5 (and probably other versions), and `cachetools/keys.py` already has
```
_all__ = ('hashkey', 'typedkey')
```
Since I don't use Pycharm myself, I don't thinks there's much I can do...

**Comment by timrichardson** [comment]
I have reported this as a pycharm bug. It is the only package that I have ever seen the problem. Hopefully JetBrains can at least change the error to a style warning.

**Comment by JIAQIA** [comment]
You can add "  # noqa" after from cachetools.keys import hashkey.
have a try
