### ISSUE TITLE
Greedy caching?

### ISSUE THREAD

**Issue by shaunc** [tkem/cachetools#202]
Thank you for this nifty library! I'm wondering if I can use/extend this library for "greedy" to-disk caching -- marked function results are cached to disk immediately; in-memory values would be still available, but also, the program could be rerun without repeating cached calculation.

The use case is a machine learning workflow tool.

As far as extending the library, I'm thinking I could:

1) extend a cache, writing __missing__ and initializing
2) write my own wrapper around the method wrapper, which used the hashkey to generate a disk-based key. I'd want to specialize subdirectories by class... which I guess would be possible.

Does that make sense? Any suggestions? Should I rather be looking at something else?

Thanks!

**Comment by tkem** [comment]
Regarding disk-based caching, I think several options werde discusses in #128.
