### ISSUE TITLE
How can I get the cache expiration time?

### ISSUE THREAD

**Issue by Andrexxelles** [tkem/cachetools#206]
Imagine a situation that I created a cache with a lifetime.
How can I get the lifetime of the cache.

**in docs**:
_classcachetools.TTLCache(maxsize, ttl, timer=time.monotonic, getsizeof=None)_

_ttl_
The time-to-live value of the cache’s items.get ttl ?

How get ttl ?

**Comment by tkem** [comment]
Like so:
```pycon
>>> from cachetools import TTLCache
>>> c = TTLCache(10, 10)
>>> c.ttl
10
```
