### ISSUE TITLE
support for file or database-backed cached?

### ISSUE THREAD

**Issue by cjw296** [tkem/cachetools#212]
Would it be considered to add either file or, perhaps database (eg: redis) backed stores for the caches this package provides?
Quick iteration of coding often requires process restarts, and unless I've missed something in the docs, this means that all caches are lost.

**Comment by tkem** [comment]
There are several packages that provide cachetools-compatible file-based implementations. 
See for example https://github.com/tkem/cachetools/issues/128.
I've also heard about at least one using redis, but can't remember the details.

**Comment by majidaldo** [comment]
Why would this need an extention? Couldn't cachetools *Cache's just accept a dictionary 'store' argument? Right now it's hidden under `_Cache_data`.
