### ISSUE TITLE
Add support for datetime.timedelta  for TTLCache TTL

### ISSUE THREAD

**Issue by john-bodley** [tkem/cachetools#216]
I realized that `cachetools` is not typed, but I was wondering whether the `ttl` argument for the `TTLCache` class should also support a `datetime.timedelta` object for specifying (and preferably storing) the TTL, i.e., 

```python
from datetime import timedelta


class TTLCache(Cache):
    """LRU Cache implementation with per-item time-to-live (TTL) value."""

    def __init__(self, maxsize, ttl: Union[int, timedelta], timer=time.monotonic, getsizeof=None):
       self.__ttl = timedelta(seconds=ttl) if isinstance(ttl, int) else ttl
       ...
```

The reason I ask is using an `int` for encoding the TTL is somewhat difficult to grok as i) it is not apparent what the units are, and ii) larger TTL become hard to comprehend resulting in people including a comment for readability like, 

```python
@cached(cache=TTLCache(maxsize=1024, ttl=86400)) # 24 hours
```

or 

```python
@cached(cache=TTLCache(maxsize=1024, ttl=60 * 60 * 24)) # 24 hours
```

rather than simply writing

```python
@cached(cache=TTLCache(maxsize=1024, ttl=timedelta(hours=24)))
```

**Comment by tkem** [comment]
The `ttl` argument has to be compatible with the result of the `timer` function, at least so that it can be added to and the result compared with `timer()`, so you could try for example (not tested)
```
import cachetools
import datetime

c = cachetools.TTLCache(maxsize=10, ttl=datetime.timedelta(seconds=10), timer=datetime.datetime.now)
```
Typings support for `cachetools` is provided by [typeshed](https://github.com/python/typeshed), but expressing these kinds of dependencies isn't so easy, apparently, so `ttl` is just `float` there. Maybe you can contribute to improve the situation over there?

**Comment by tkem** [comment]
However, this would probably be a nice addition to the `TTLCache` docs, to show proper use of the `timer` argument.

**Comment by tkem** [comment]
Unit tests should also be added for this.

**Comment by sk-** [comment]
It would be great if timedeltas ttl could be supported without having to define a custom timer.

The constructor could be changed to include the following:

```python
if isinstance(ttl, datetime.timedelta):
  self.ttl = ttl.total_seconds()
```

See https://docs.python.org/3/library/datetime.html#datetime.timedelta.total_seconds

**Comment by tkem** [comment]
@sk- : Thought about this myself, but `datetime` stuff is only one option, having `ttl` and `timer` being freely customizable adds more possibilities, as shown e.g. in the unit tests.
So the default make sense IMHO, but I wouldn't add special handling for any other timestamp/timedelta APIs, at least for now.
