### ISSUE TITLE
Version 4.2.3 breaks other packages

### ISSUE THREAD

**Issue by tzickel** [tkem/cachetools#225]
I do not know if such a minor release has the intended consequences of breaking the API contract, but here is a project that just stopped working because of it:

https://github.com/wimglenn/johnnydep/blob/8c3f1e9eb81bc43db3b5f9d1f0b4b3a0c187eb82/johnnydep/pipper.py#L21

I assume this commit is at fault:
https://github.com/tkem/cachetools/commit/be507a6234ac6f48ed84052a414e38dfb22aaa8a

@wimglenn

**Comment by wimglenn** [comment]
Oof, that is quite a backwards break for a minor bump v4.2.2 -> v4.2.3
The fix is easy (just change import statements) but maybe this release should be yanked and compat shims put in..

**Comment by tkem** [comment]
`cachetools` uses semantic versioning, and the minor version change to 4.2.3 IMHO correctly indicates that the [public API](https://cachetools.readthedocs.io/en/stable/) did _not_ change.

The `cachetools.ttl` submodule was an undocumented implementation detail. Documentation including code examples use `from cachetools import TTLCache`, and have done so from the start. Why `johnnydep` chose to use `cachetools.ttl` I don't know, but this was never officially supported, nor even mentioned in the documentation.

**Comment by wimglenn** [comment]
Yeah, my bad - the autodoc always mentioned `cachetools.TTLCache`.

It might be that some IDEs which automatically write your import statements just take them from the module where the class is defined, not sure? There is sort of a convention in Python that anything without a leading underscore is fair game. [Here are ~100 others making same mistake](https://github.com/search?q=%22from+cachetools.ttl+import+TTLCache%22&type=code).

I'll note that I did mention those supposed "existing APIs" in comment  https://github.com/tkem/cachetools/issues/146#issuecomment-536062696

**Comment by tkem** [comment]
Well, sorry for the inconvenience - I didn't think this would have much of an impact, but I guess you may be right about IDEs doing autocompletion. OTOH, the vast majority of users [seem to do it right](https://github.com/search?q=%22from+cachetools+import+TTLCache%22&type=Code&ref=advsearch&l=&l=), and AFAICS most of the affected repos use copies/variants(?) of same code base, so who knows...

I usually do follow the double underscore (or for class members, double underscore) convention, except for "private" submodules. But those were just a bad habit of mine, coming from languages like C/C++, and I'm trying to give up on that.

And yes, I completely missed your comment in #146, sorry for that!

**Comment by tkem** [comment]
Temporarily reopened so others, who are affected by this, will find this more easily.

**Comment by risenberg-cyberark** [comment]
It broke our usage too. You should either support it backwards or change it to v5 as it's a breaking change.

**Comment by tkem** [comment]
Apparently @wimglenn was right about Hyrum's law... I guess I'll add some submodule shims for backward compatibility, but please _do_ fix your imports ASAP.

**Comment by castarco** [comment]
> The cachetools.ttl submodule was an undocumented implementation detail.

That's misleading. Even if it was not "documented", the API was publicly exported, and it was available through autocomplete tooling.

**Comment by wimglenn** [comment]
@tkem  No big deal, but there is a slightly nicer way to indicate deprecation (details in https://github.com/tkem/cachetools/pull/226)

**Comment by tkem** [comment]
@wimglenn: Yes, of course. I know, or I [knew](https://github.com/tkem/cachetools/blob/v1.1.6/cachetools/func.py#L33) at least... Kind of rushed this out today - thanks for pointing this out!
