### ISSUE TITLE
Redis Integration

### ISSUE THREAD

**Issue by JoranHonig** [tkem/cachetools#230]
I was looking for a cool project around hacktoberfest, this is kind of a proposal for that 🙌 

I'd like to add some redis cache implementations to the cachetools library, so that people can easily migrate from using a local cache to a distributed redis cache.

There are a few (seemingly unsupported) libraries around that already implement redis support for cachetools, but I think it'd be super nice to add redis support to the main cachetools lib. 

I'd also propose using extras to keep dependencies to a minimum for users that don't want to use redis.

Let me know what you think 🙌

**Comment by JoranHonig** [comment]
Yeaaah, I should read existing issues before I post https://github.com/tkem/cachetools/issues/147.

The offer still stands 👍

**Comment by luisdavim** [comment]
I know this issue is closed but just leaving this here in case someone, like me, comes across it from googling.
There's a package that extends `cachetools` with support for Redis and Memcached, the integration is pretty seamless.
Have a look at https://github.com/zx80/cachetools-utils
