### ISSUE TITLE
Ignore KeyError in cache

### ISSUE THREAD

**Issue by onebula** [tkem/cachetools#231]
Although cachetool is not thread safe, I find a key point is that cachetools will raise keyerror when it runs at del or pop operations if a key is just expired by other threads. Since these key-values are no longer cached, a more proper way is to ignore keyerror. I think it would be a solution to make cachetools more stable in multithreaded code, in consideration of the performance decrease with lock.

Here are some examples for modification

```
class Cache(collections.abc.MutableMapping):
    def __delitem__(self, key):
        size = self.__size.pop(key)
        #del self.__data[key]
        #self.__currsize -= size
        try:
            del self.__data[key]
        except KeyError:
            pass
        else:
            self.__currsize -= size

class LRUCache(Cache):
    def __delitem__(self, key, cache_delitem=Cache.__delitem__):
        cache_delitem(self, key)
        #del self.__order[key]
        self.__order.pop(key, None)

class TTLCache(Cache):
    def __delitem__(self, key, cache_delitem=Cache.__delitem__):
        cache_delitem(self, key)
        #link = self.__links.pop(key)
        #link.unlink()
        #if link.expire < self.__timer():
        #    raise KeyError(key)
        try:
            link = self.__links.pop(key)
        except KeyError:
            pass
        else:
            link.unlink()
            if link.expire < self.__timer():
                pass
```

**Comment by onebula** [comment]
As many users found, multithread is a common case that cachetools fails. Maybe other cases in single thread code could lead to the same situation. 
The major reason is that the delitem function could break due to KeyError:
1. As shown in examples, replacing del key by cache.pop(key, None) or just to ignore KeyError in delitem related functions, while the other major function of cachetools still keeps. 
2. I suggest using a global configuration to handle this situation, and printing warning to stdout or log instead of stop service. 
This could be more natural for cache. Other users may also benefit from this modification.

**Comment by tkem** [comment]
As stated in [the docs](https://cachetools.readthedocs.io/en/stable/#cache-implementations):
> Please be aware that all these classes are not thread-safe. Access to a shared cache from multiple threads must be properly synchronized, e.g. by using one of the memoizing decorators with a suitable lock object.

"Not thread-safe" means that a cache's internal data structure may become corrupt when accessed concurrently without proper synchronization, leading to memory leaks and other nasty stuff. Raising `KeyError` is only an indication that far worse things may have already happened without you noticing. So eliminating these is not an option.
