### ISSUE TITLE
Ignoring function arguments with ttl_cache

### ISSUE THREAD

**Issue by floatingpurr** [tkem/cachetools#236]
Hi folks! I need to ignore some params of a function decorated with `@ttl_cache`

E.g.:

```python
@ttl_cache(maxsize=1024, ttl=600)
def my_func(foo, ignore_bar, ignore_baz):
    # do stuff
```

Working that way, I get this: 
```python
>>> my_func("foo", "ignore_bar", "ignore_baz")         # cache miss
>>> my_func("foo", "ignore_bar", "ignore_baz")         # cache hit
>>> my_func("foo", "ignore_bar_bar", "ignore_baz_baz") # cache miss!
```

What I need:

```python
>>> my_func("foo", "ignore_bar", "ignore_baz")         # cache miss
>>> my_func("foo", "ignore_bar", "ignore_baz")         # cache hit
>>> my_func("foo", "ignore_bar_bar", "ignore_baz_baz") # cache hit!!!!!
```

It looks like there isn't any straightforward way to do that (see [this thread](https://stackoverflow.com/questions/70535336/how-to-ignore-function-arguments-with-cachetools-ttl-cache) in SO), but I might be wrong

**Comment by tkem** [comment]
Please see the answer on SO, posting generic questions there and reserving  GitHub Issues for bug reports is encouraged ;-)

**Comment by floatingpurr** [comment]
Ok, got it. Thank you @tkem :)
