### ISSUE TITLE
Add type annotations

### ISSUE THREAD

**Issue by gaborbernat** [tkem/cachetools#238]
This would be welcomed 👍

**Comment by tommyjcarpenter** [comment]
This would be extremely helpful, as I have to slap mypy `ignores` on cachetools lines and we heavily use cachetools along with `mypy --strict`; so 👍 from me!

**Comment by gaborbernat** [comment]
Note in the meantime you can install https://pypi.org/project/types-cachetools/ to work around the issue, but in long term would be nice not have to do it.

**Comment by tommyjcarpenter** [comment]
@gaborbernat thanks thats awesome!

**Comment by tkem** [comment]
See https://github.com/tkem/cachetools#installation.

**Comment by ThirVondukr** [comment]
@tkem Sorry for bumping such an old issue, but why rely on a stub package instead of using type hints in the codebase?
