### ISSUE TITLE
Mismatch between arguments for TTLCache

### ISSUE THREAD

**Issue by DatGuy1** [tkem/cachetools#239]
The [documentation](https://github.com/tkem/cachetools/blob/master/docs/index.rst) says to use TTLCache(number, timedelta), but both [typeshed](https://github.com/python/typeshed/blob/master/stubs/cachetools/cachetools/__init__.pyi#L49) and [the README](https://github.com/tkem/cachetools/blob/master/README.rst) use two numbers.

I'm not sure if timedelta has an implicit conversion, but my IDE complained about it.

**Comment by tkem** [comment]
> By default, the time-to-live is specified in seconds and time.monotonic() is used to retrieve the current time.  A custom timer function can also be supplied...
https://cachetools.readthedocs.io/en/stable/#cachetools.TTLCache

The intent of the example was to demonstrate use of a custom timer with a non-numeric `ttl` argument. But I can now see how this may cause confusion.

It would probably be better to provide an examples for standard use first (numeric `ttl` in seconds with default `timer`), to make clear that both variants are valid.
