### ISSUE TITLE
How to limit the whole memory size of the cache

### ISSUE THREAD

**Issue by fangxlmr** [tkem/cachetools#241]
Say I have quite large (or a large number of) keys that takes a lot of memory, I want to limit the whole cache size in terms of mem. I then got 2 questions:

1. it doubles the key storage since it stores keys twice
https://github.com/tkem/cachetools/blob/ab9e8af0d506759332a2d1a5ae9d36feae844fda/src/cachetools/__init__.py#L57

2. though I can set `getsizeof=sys.getsizeof`, it only limit value size whereas key size has no restriction

**Comment by tkem** [comment]
@fangxmlr: Yes, `getsizeof` assumes that _values_ are the dominant size factor. Please see #169 for further information. Caches that may store keys multiple times for indexing are one reason for this design decision.
