### ISSUE TITLE
Add basic documentation for all classes arguments in the docstring

### ISSUE THREAD

**Issue by hellocoldworld** [tkem/cachetools#244]
This way, IDEs may display it as contextual help, saving developers from having to switch to a browser and lookup for that information in the documentation.

If you think this is a good idea, I'd be happy to work on a PR

**Comment by tkem** [comment]
@hellocoldworld: Sorry, I'm not sure I understand - can you provide an example of what you suggest to add?

**Comment by tkem** [comment]
Closed due to inactivity.
