### ISSUE TITLE
PyCharm can't find reference 'TLRUCache' in 'init.pyi'

### ISSUE THREAD

**Issue by beibao233** [tkem/cachetools#248]
**Describe the bug**
The documentation section for TLRUCache may be incorrect
When I was developing with cachetools, I found that the TLRUCache class does not exist
(I installed this package using pip install cachetools)

I have to check past issues to know that TTLCache has integrated TRLUCache

Am I doing something wrong to not be able to import this class or does this class not exist in the latest version?

```python
from cachetools import TLRUCache
```

Oh right. Im using Python 3.10 

Thank you and all the contributors for your hard work!

**Comment by tkem** [comment]
Can't confirm:
```
$ pip3 install cachetools
Collecting cachetools
  Downloading cachetools-5.2.0-py3-none-any.whl (9.3 kB)
Installing collected packages: cachetools
Successfully installed cachetools-5.2.0
$ python3 
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from cachetools import TLRUCache
>>> TLRUCache
<class 'cachetools.TLRUCache'>
>>> 
```
What's your `cachetools.__version__`?

**Comment by beibao233** [comment]
Sorry, My bad. This class is in my local package.

Im using PyCharm. And it tell me
```
Cannot find reference 'TLRUCache' in '__init__.pyi' 
```
And I think that isn't existed
(I am Chinese, and in that time is 0:00 for me so my brain does not doing it's job)

Now Issue name need to change to PyCharm can't find reference 'TLRUCache' in '__init__.pyi' 

And my ```cachetools.__version__``` is '5.2.0'

**Comment by beibao233** [comment]
pycharm will not stop the code from running but the code hints for TLRU will not be displayed.

**Comment by tkem** [comment]
I don't know about PyCharm, so sorry, I can't be of much help here.
