### ISSUE TITLE
`cachetools.func` decorators share cache when decorating multiple functions.

### ISSUE THREAD

**Issue by PhilMarsh** [tkem/cachetools#255]
**Describe the bug**
When one instance of a `cachetools.func` decorator is applied to multiple `user_function`s, all decorated `user_function`s share one cache.

This affects all aspects of the wrapped function's interface. The most obvious result is that two otherwise-unrelated functions can return each other's results. Additionally `.cache_info()` can produce confusing results: `currsize` is shared between the wrapped functions, but `hits` and `misses` are unique to each function. `.cache_clear()` shows this as well: `currsize` is reset for all functions, but `hits` and `misses` are reset only for the function object that `.cache_clear()` was called on.

In contrast, one instance of the standard `functools.lru_cache` gives a unique cache to each `user_function` it decorates.

The docs do describe `cachetools.func` as "a similar API" to `functools`, not necessarily an exact replica. So I can't say this is wrong just because it "disagrees with `functools`". But I do think the `functools` approach yields the "least surprising" result for users.

Note that I don't think this is an issue for the core `cachetools.cached()` decorator. `cachetools.cached()` requires a `cache` arg from the caller, making it implicitly clear that the object is being shared already (by the caller). This is only an issue for `cachetools.func` because the cache objects are being created implicitly and the scope of their lifetime is not obvious.

**Expected result**
`cachetools.func` decorators should always produce isolated wrapped functions, with their own unique caches.

**Actual result**
When one instance of a `cachetools.func` decorator is applied to multiple `user_function`s, all decorated `user_function`s share one cache.

**Reproduction steps**
```python
import cachetools.func

cache = cachetools.func.lru_cache()

@cache
def foo(x):
    print(f"cache miss foo: {x}")

@cache
def bar(x):
    print(f"cache miss bar: {x}")

foo(1)  # prints "cache miss foo: 1"
foo(1)  # prints nothing
bar(1)  # prints nothing

foo.cache_info()  # CacheInfo(hits=1, misses=1, maxsize=128, currsize=1)
bar.cache_info()  # CacheInfo(hits=1, misses=0, maxsize=128, currsize=1)

foo.cache_clear()

foo.cache_info()  # CacheInfo(hits=0, misses=0, maxsize=128, currsize=0)
bar.cache_info()  # CacheInfo(hits=1, misses=0, maxsize=128, currsize=0)

bar(1)  # prints "cache miss bar: 1"

foo.cache_info()  # CacheInfo(hits=0, misses=0, maxsize=128, currsize=1)
bar.cache_info()  # CacheInfo(hits=1, misses=1, maxsize=128, currsize=1)
```
Compare to `functools`:
```python
import functools

cache = functools.lru_cache()

@cache
def foo(x):
    print(f"cache miss foo: {x}")

@cache
def bar(x):
    print(f"cache miss bar: {x}")

foo(1)  # prints "cache miss foo: 1"
foo(1)  # prints nothing
bar(1)  # prints "cache miss bar: 1"

foo.cache_info()  # CacheInfo(hits=1, misses=1, maxsize=128, currsize=1)
bar.cache_info()  # CacheInfo(hits=0, misses=1, maxsize=128, currsize=1)

foo.cache_clear()

foo.cache_info()  # CacheInfo(hits=0, misses=0, maxsize=128, currsize=0)
bar.cache_info()  # CacheInfo(hits=0, misses=1, maxsize=128, currsize=1)

bar(1)  # prints nothing

foo.cache_info()  # CacheInfo(hits=0, misses=0, maxsize=128, currsize=0)
bar.cache_info()  # CacheInfo(hits=1, misses=1, maxsize=128, currsize=1)
```

**Comment by tkem** [comment]
@PhilMarsh: Please use
```
@cachetools.func.lru_cache()
def foo(x):
    print(f"cache miss foo: {x}")

@cachetools.func.lru_cache()
def bar(x):
    print(f"cache miss bar: {x}")
```
or
```
@cachetools.func.lru_cache
def foo(x):
    print(f"cache miss foo: {x}")

@cachetools.func.lru_cache
def bar(x):
    print(f"cache miss bar: {x}")
```
if you simply want to use default decorator parameters.

Using
```
cache = cachetools.func.lru_cache()
```
you instantiate a decorator with a specific cache instance, which will then indeed be shared across function.
However, I haven't seen this usage before, and I'm actually quite surprised `functools.lru_cache` handles this differently. I'll look into this in more detail, though.
