### ISSUE TITLE
debug logging

### ISSUE THREAD

**Issue by snarfed** [tkem/cachetools#259]
> Sorry, but `cachetools` is not accepting feature requests at this time.

Understood! Just filing this to track and start the discussion...

Debug logging would be a useful addition for checking that caches are working like you expect, keys are being generated right, etc. I'd love to be able to `logging.getLogger('cachetools').setLevel(logging.DEBUG)` and then see logs for every cache lookup, whether it's a hit or miss, the resulting value, etc.

**Comment by tkem** [comment]
Thanks for your interest, but well...
Would you also expect to, let's say `collections.OrderedDict` to use logging facilities? Or plain `dict` even?
`cachetools` is far to low-level to add the overhead. Period ;-)
