### ISSUE TITLE
[security] Set minimum permissions for workflows

### ISSUE THREAD

**Issue by gabibguti** [tkem/cachetools#261]
Setting minimum permissions for workflows is important to keep your repository safe against supply-chain attacks. I see you have one workflow, `ci.yml`, and it does not need many permissions to run it's actions, so `contents: read` permission should be enough. By default, GitHub gives higher permissions to workflows but [recommends adjusting them](https://docs.github.com/en/actions/security-guides/automatic-token-authentication).

This is considered good-practice and is also recommended by other security tools, such as [Scorecards](https://github.com/ossf/scorecard) and [StepSecurity](https://github.com/step-security).

##### Additional Context
I'm Gabriela and I work on behalf of Google and the OpenSSF suggesting supply-chain security changes :)
If you agree with the changes, I can open a PR.

**Comment by tkem** [comment]
@gabibguti: PR would be welcome, thank you!
