### ISSUE TITLE
Proposed Google OSS-Fuzz Integration

### ISSUE THREAD

**Issue by sg3-141-592** [tkem/cachetools#264]
Hi there,

In this PR I've done an initial integration of Cachetools into the Google OSS-Fuzz project https://github.com/google/oss-fuzz/pull/9957 .

Coverage is pretty good. No bugs found so far.

I was wondering if you would like to integrate continuous fuzzing into cachetools by way of OSS-Fuzz?

If you would like to integrate, the only thing I need is a list of email(s) that will get access to the data produced by OSS-Fuzz, such as bug reports, coverage reports and more stats. Notice the emails affiliated with the project will be public in the OSS-Fuzz repo, as they will be part of this configuration file [project.yaml](https://github.com/google/oss-fuzz/blob/bd07f0350562a27b3ab38bb7e35ea475bdc0ffd5/projects/cachetools/project.yaml).

**Comment by tkem** [comment]
@sg3-141-592: I'm not familiar with OSS-Fuzz, but everything trying to improve code quality gets my squeal of approval ;-)

Since this is _not_ a PR, I'd like to see what changes to the project/code would have to be made before I give a final veridct, though.

**Comment by sg3-141-592** [comment]
Thanks @tkem ,

For the [PR linked above](https://github.com/google/oss-fuzz/pull/9957), this would integrate your library into the [OSS-Fuzz'es](https://google.github.io/oss-fuzz/) regular overnight fuzzing. This is a project to try and find security and stability issues in key open source libraries.

These are the reports for all of the latest fuzzed projects https://storage.googleapis.com/oss-fuzz-introspector/index.html .

I wasn't looking to make any changes to cachetools. Instead we nightly pull the latest cachetools from Github and run the fuzzer against it ([fuzz_cached.py](https://github.com/google/oss-fuzz/blob/bd07f0350562a27b3ab38bb7e35ea475bdc0ffd5/projects/cachetools/fuzz_cached.py)). The fuzzer is trying lots of different cache types and sizes against your Fibonacci sequence example function.

The project has a separate portal only accessible by the users listed in the [project.yaml](https://github.com/google/oss-fuzz/blob/bd07f0350562a27b3ab38bb7e35ea475bdc0ffd5/projects/cachetools/project.yaml) file where you can see any exceptions or errors the Fuzzer manages to generate. You get an e-mail notification when a new issue is found.

You can have fuzz testing as part of the Pull Request process using [Github Actions](https://google.github.io/oss-fuzz/getting-started/continuous-integration/). I think adding it to the overnight OSS-Fuzzing would be a lighter touch way to see if you're getting any value from fuzzing the library or not before changing anything in the cachetools project.

If you're happy to go ahead I can get this integrated into the overnight runs, and if you've got any e-mail addresses you'd like notified I'll add them to [project.yaml](https://github.com/google/oss-fuzz/blob/bd07f0350562a27b3ab38bb7e35ea475bdc0ffd5/projects/cachetools/project.yaml).

**Comment by tkem** [comment]
@sg3-141-592 : Thanks for elaborating, I got confused since you were referring to the PR in OSS-Fuzz. 
But I think I'm slowly to understand now...

Please go ahead, but at least for now I'd prefer not to be notified by email - I guess I can check results via the link you posted above.

**Comment by sg3-141-592** [comment]
Thanks @tkem , I'll let you know if we get any interesting results.
