### ISSUE TITLE
Do not range-pin dependencies in setup.cfg

### ISSUE THREAD

**Issue by woutervh** [tkem/cachetools#269]
In setup.cfg, you specify cachetools is forbidden to be installed  in the non-existing, hypothetical python 4.0.
As a result you force any project using this package as a dependency to forbid any python4.0-compatibility as well. For no reason whatsoever.  Range-pinning is never intended to *guarantee* compatibility.

PROBLEM:
```
python_requires = ~= 3.7
```

SOLUTION:
```
python_requires = >= 3.7
```
For a detailed write-up, see https://iscinumpy.dev/post/bound-version-constraints/ for a detailed write-up.

Range-pinning conflates the concept of abstract dependencies versus concrete dependencies .
In pyproject.toml / setup.py / setup.cfg we should define the abstract dependencies,
while poetry.lock and requirements.txt contain the list of concrete dependencies to recreate an reproducible environment

Example:
![image](https://user-images.githubusercontent.com/469509/235364690-2f5f820c-7f57-42c4-ba28-abaf02cdadeb.png)

**Comment by tkem** [comment]
Fixed with PR #270.

@woutervh Thanks for pointing this out, and providing the references.
