### ISSUE TITLE
Letting the user decide the TTL

### ISSUE THREAD

**Issue by impredicative** [tkem/cachetools#272]
I am currently using the TTL decorator over functions. What would be the best way to let the user decide the TTL? I don't want it predecided for me by the function itself. This is a different way of thinking about expiry. The acceptable TTL can be different for different use cases of the user.

For example, consider this call:

```python
# Normal call: my_fun(*args, **kwargs)

# TTL-controlling calls:
fresh_result = cachetools.apply_ttl(0.1, target=my_fun, *args, **kwargs)
cached_result = cachetools.apply_ttl(1.0, target=my_fun, *args, **kwargs)
```

**Comment by tkem** [comment]
If you're referring to the `func.ttl_cache` decorator, the TTL can be set via the `ttl` parameter.
Please see the documentation for details: https://cachetools.readthedocs.io/en/latest/#module-cachetools.func
