### ISSUE TITLE
cachedmethod unable to use threading.lock

### ISSUE THREAD

**Issue by npezolano** [tkem/cachetools#274]
```
Python 3.10.11 cachetools 5.3.1
```

You can't use `threading.lock` with `cachedmethod` since the lock object is not callable and takes no arguments and the `cachetools` code passes self to the lock. See the example below:

```py
import cachetools
import operator
from threading import Lock

class MyClass(object):
    def __init__(self):
        self.cache = cachetools.LRUCache(maxsize=10) 
    
    @cachetools.cachedmethod(operator.attrgetter('cache'), lock=Lock())
    def calc(self, n):
        print("Calculating", n)
        return 1*n
        
c = MyClass()
c.calc(1) 
```

```py

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[23], line 2
      1 c = MyClass()
----> 2 c.calc(1)

File ~/anaconda3/lib/python3.10/site-packages/cachetools/__init__.py:819, in cachedmethod.<locals>.decorator.<locals>.wrapper(self, *args, **kwargs)
    817 k = key(self, *args, **kwargs)
    818 try:
--> 819     with lock(self):
    820         return c[k]
    821 except KeyError:

TypeError: '_thread.lock' object is not callable

```

**Comment by npezolano** [comment]
https://github.com/tkem/cachetools/pull/275

**Comment by tkem** [comment]
Form the [docs](https://cachetools.readthedocs.io/en/latest/#cachetools.cachedmethod):

> The main difference between this and the [cached()](https://cachetools.readthedocs.io/en/latest/#cachetools.cached) function decorator is that cache and lock are not passed objects, but functions. Both will be called with self (or cls for class methods) as their sole argument to retrieve the cache or lock object for the method’s respective instance or class.

The main purpose of `@cachedmethod` is to have per-instance caches. Specifying `lock=Lock()` in the decorator would use a single global `Lock` instance for _all_ decorated methods, so instead I'd expect you'd want use a per-instance lock, too, e.g. something like `lock=operator.attrgetter('lock')`.

If you _really_ want to use a global `Lock` instance, adding something like a `get_lock(self)` method to your class which simple ignores `self` and always returns the same lock shouldn't be too much trouble, but I'd wonder why you'd do that.

Maybe the examples should be updated to show correct use of the `lock` parameter with `@cachedmethod`, to make this more clear...
