### ISSUE TITLE
[security] Reference actions by commit SHA

### ISSUE THREAD

**Issue by gabibguti** [tkem/cachetools#287]
Referencing actions by commit SHA in GitHub workflows, guarantees you are using an immutable version. Actions referenced by tags and branches are more vulnerable to attacks, such as the tag being moved to a malicious commit, a malicious commit being pushed to the branch or typosquatting.

Although there are pros and cons for referencing by branch, tag and commit SHA, GitHub understands [SHAs are more reliable](https://docs.github.com/en/actions/learn-github-actions/finding-and-customizing-actions#using-shas), as does [Scorecard](https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies) security tool, specially for third-party actions.

In `ci.yml`, we use the GitHub actions `actions/checkout@v4` and `actions/setup-python@v4` and the third-party action `codecov/codecov-action@v3`. To refence by commit SHA, we would change, for example, `actions/checkout@v4` to `actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac` followed by a comment `# v4.0.0` to keep the version readable.

If you agree with the changes, I can open a PR.

##### Additional Context

Hi again! I'm Gabriela and I work on behalf of Google and the OpenSSF suggesting supply-chain security changes :)

**Comment by tkem** [comment]
Hi @gabibguti, how does this work with @kurtmckee's [recent PR](https://github.com/tkem/cachetools/pull/282) to keep GitHub action versions updated?

**Comment by kurtmckee** [comment]
Looks like [Dependabot supports bumping SHAs _and_ adding a comment for the updated tags](https://github.blog/changelog/2022-10-31-dependabot-now-updates-comments-in-github-actions-workflows-referencing-action-versions/).

I'll confirm this behavior on my own projects and see how Dependabot behaves. :+1:

**Comment by kurtmckee** [comment]
I found a bug in Dependabot while testing this on my own projects (and [submitted a PR to resolve the issue](https://github.com/dependabot/dependabot-core/pull/8127)).

However, cachetools' CI files don't use explicitly-quoted strings so this bug won't affect cachetools. I'll submit a PR to switch to SHAs, together with a version comment.

**Comment by gabibguti** [comment]
Hi! Sorry about the delay to answer. Good concern @tkem and @kurtmckee already answered and is completly right. Dependabot can update the SHAs and the following comment that keeps the version humanly readable (e.g. `#4.1.0`), and the Dependebot configuration that kurtmckee created already covers such updates.

Here's an example PR of dependabot updating commit SHAs: https://github.com/ossf/scorecard/pull/3453/files

BTW nice catch on the bug!

**Comment by gabibguti** [comment]
Also, Dependabot is introducing [grouped version updates](https://github.blog/changelog/2023-06-30-grouped-version-updates-for-dependabot-public-beta/), if that helps you in any way.
