### ISSUE TITLE
`cachetools.keys.typedmethodkey`?

### ISSUE THREAD

**Issue by kuraga** [tkem/cachetools#296]
There are:
- `cachetools.keys.hashkey`,
- `cachetools.keys.methodkey`,
- `cachetools.keys.typedkey`.

Should be there the `cachetools.keys.typedmethodkey`? Thanks!

**Comment by tkem** [comment]
@kuraga Thnaks for the input! `typedkey` is used in the `cachetools.func` wrappers, and nobody expressed any interest in a `typedmethodkey` so far. For the sake of completeness, however, this might be added.

**Comment by kuraga** [comment]
> For the sake of completeness, however, this might be added.

Implemented in #301.

**Comment by kuraga** [comment]
New PR: #305.
