### ISSUE TITLE
On tests disproportion

### ISSUE THREAD

**Issue by kuraga** [tkem/cachetools#302]
The `keys.hashkey` and the `keys.typedkey` decorators have both [unit](https://github.com/tkem/cachetools/blob/d991ac71b4eb6394be5ec572b835434081393215/tests/test_keys.py) and [functional](https://github.com/tkem/cachetools/blob/d991ac71b4eb6394be5ec572b835434081393215/tests/test_cached.py) tests.

But the `keys.methodkey` decorator has [functional](https://github.com/tkem/cachetools/blob/d991ac71b4eb6394be5ec572b835434081393215/tests/test_cachedmethod.py) tests only.

**Comment by tkem** [comment]
I'll look into that ASAP (whatever that may mean).

**Comment by kuraga** [comment]
Feel free to ask questions :)

**Comment by kuraga** [comment]
I meant there are no tests such as [these](https://github.com/tkem/cachetools/blob/d991ac71b4eb6394be5ec572b835434081393215/tests/test_keys.py):
```python
def test_hashkey(self, key=cachetools.keys.hashkey):
    self.assertEqual(key(), key())
    self.assertEqual(hash(key()), hash(key()))
    self.assertEqual(key(1, 2, 3), key(1, 2, 3))
    ...
```

**Comment by kuraga** [comment]
Thanks!

**Comment by tkem** [comment]
You're welcome!
