### ISSUE TITLE
Get TypeError: unhashable type: 'dict' for dict response method

### ISSUE THREAD

**Issue by andy-yu-y** [tkem/cachetools#314]
Hi,
I found this library does not support dict response method.
Could this condition be supported?
Or can someone help me to work around this issue?

@cached(cache=TTLCache(maxsize=1024, ttl=3600))
def search_for_visualizer(
    user_info: dict = Depends(verify_token),
):
    return responseDict

when call this method it report TypeError: unhashable type: 'dict'

**Comment by arunraja1** [comment]
@tkem @andy-yu-y 
 We are facing the same issue in one of our services transiently, when can we expect a fix for this

**Comment by tkem** [comment]
See https://cachetools.readthedocs.io/en/latest/#module-cachetools.keys, especially the `envkey` example.
