### ISSUE TITLE
No lock provided in cachedmethod

### ISSUE THREAD

**Issue by vaab** [tkem/cachetools#32]
In ``cachedfunc`` implementation, you are providing a ``lock`` argument, why not in ``cachedmethod`` ? 

It seems that multiple thread could be sharing the same instance of an object, and require locking facility also ? Am I wrong ?

BTW, shouldn't the locking mecanism implemented into the Cache objects ? (in this case, no need of this argument in either ``cachedfunc`` nor ``cachedmethod``).

**Comment by tkem** [comment]
See http://pythonhosted.org/cachetools/#method-decorators:
> Multiple methods of an object or class may share the same cache object, but it is the user’s responsibility to handle concurrent cache access in a multi-threaded environment.
With cached methods, the cache object is passed from "outside" and not under control of the decorator. 
That's why there are no provisions for locking.

**Comment by tkem** [comment]
The intention for `@cachedmethod` was also that it should work with *any* mutable mapping passed as `cache`, including plain `dict` and `weakref.WeakValueDictionary`. Now, this reminds me that I wanted to write some unit tests and put that in the docs ;-)
