### ISSUE TITLE
Evict callback

### ISSUE THREAD

**Issue by Iulian7** [tkem/cachetools#35]
Hi,

I feel what is missing from this library is an evict callback. When an item is evicted, maybe you want to do something with the item - for example persist it to storage somewhere because it might have changed during its lifetime in the cache. 

Do you have something like this planned?

**Comment by tkem** [comment]
Usually, `popitem()` is called to make room for new items when a cache is full, so I guess you could override that method to perform some action on the removed item(s).

**Comment by Iulian7** [comment]
Aha yea, I was just going through the code. Overriding `popitem()` seems to be the perfect place for this. Thanks.

**Comment by tkem** [comment]
You're welcome. May be hinting at this use case for `popitem` in the docs in the future.

**Comment by tkem** [comment]
After reviewing the docs, the fact that cache implementations do/should use `popitem()` to make room for new cache items is actually "hidden" in the `Cache` base class documentation. So perhaps putting this in the introduction section or at the top of the "Cache Implementations" section would make this more clear.
@Iulian7: If this was spelled out more prominent in the docs, maybe you wouldn't had to go through the code? Any suggestions for making this more clear?

**Comment by Iulian7** [comment]
@tkem Yes if this was clearer in the docs I would not have gone through the code. Perhaps there should be an "extensibility" section in the docs?

**Comment by tkem** [comment]
I'll see what I can do.
