### ISSUE TITLE
Feature request: manually clearing cache

### ISSUE THREAD

**Issue by aartur** [tkem/cachetools#38]
It seems that currently you can only pop individual items by a key.

It also looks like a `cache` object isn't saved by `cachedfunc` decorator into a wrapped function, it's done in `cachedmethod` only.

**Comment by tkem** [comment]
All cache classes support the `clear` method.

**Comment by aartur** [comment]
Oh, I didn't see it, because it's inherited from `MutableMapping`.

And `clear_cache` is exposed by `cachedfunc` but not the cache object itself, like it's done in `cachedmethod`.

**Comment by tkem** [comment]
Actually, you shouldn't be using `cachedfunc`, since its not part of the public API, and will likely be removed in the next version. Use one of the officially supported function decorators instead, e.g. `lru_cache `.

**Comment by aartur** [comment]
But `lru_cache` consists of a call to `cachedfunc`, so it also doesn't expose `cache` object.

**Comment by tkem** [comment]
The function decorators provide the same interface as Python 3's `lru_cache`. That's why they differ from `cachedmethod`.
Future versions of `cachetools` *may* provide a generic `cachedfunc` decorator, but its interface will differ from the current (private) `cachedfunc`.

**Comment by aartur** [comment]
Thanks for explanations, I didn't know the library mimics Python 3's interface. It seems to me that a reference to an underlying cache object should be exposed when a decorator is used (if having a good API is the goal and not Python 3 compatibility).

**Comment by tkem** [comment]
Access to the cache object will be considered for future versions. Thanks for your interest!
