### ISSUE TITLE
Pickle improvements

### ISSUE THREAD

**Issue by marcovc** [tkem/cachetools#45]
Hi,

Thanks for your cache implementation.  I was hitting the "maximum recursion limit" when pickling a large LRU cache. I think this is due to the recursive nature of the double linked list you use for sorting the values. My workaround was to pickle only this list using a loop, instead of the list+dict (this also saves space).

The code below was added to lru.py to fix the problem. I'm posting it here in case you're interested.

Thanks!
Marco

```python
  def __getstate__(self):
        c = self.__root
        l = []
        while c.prev!=self.__root:
            l.append((c.prev.key,c.prev.value))
            c = c.prev
        state = {
          "currsize" : self.currsize ,
          "maxsize" : self.maxsize,
          "ordering" : l
        }
        if hasattr(self,"__missing"):
            state["missing"] = self.__missing
        else:
            state["missing"] = None
        if hasattr(self,"__getsizeof"):
            state["getsizeof"] = self.__getsizeof
        else:
            state["getsizeof"] = None
        return state
      
    def __setstate__(self,state):
        self.__init__(state["maxsize"],state["missing"],state["getsizeof"])
        for kv in reversed(state["ordering"]):
            self.__setitem__(kv[0],kv[1])
```

**Comment by tkem** [comment]
Thanks for sharing. I'll look into that when I get back from summer vacation ;-)

**Comment by tkem** [comment]
Sorry it took me so long, but I was busy with other things...
Please note that your code has some issues regarding name mangling of pseudo-private "double underscore" members, so AFAICS it won't work with custom ``missing`` or ``getsizeof``.
I ended up taking a slightly different route, which now also allows to use the default pickle protocol with Python 2.7. You might want to take a look at the updated implementation (both for LRU and TTL caches), or just update to v1.1.2 and see if that works for you.
However, thanks for putting me in the right direction!

**Comment by marcovc** [comment]
On 09/15/2015 07:25 PM, Thomas Kemmer wrote:
>
> Sorry it took me so long, but I was busy with other things...
> Please note that your code has some issues regarding name mangling of 
> pseudo-private "double underscore" members, so AFAICS it won't work 
> with custom |missing| or |getsizeof|.
> I ended up taking a slightly different route, which now also allows to 
> use the default pickle protocol with Python 2.7. You might want to 
> take a look at the updated implementation (both for LRU and TTL 
> caches), or just update to v1.1.2 and see if that works for you.
> However, thanks for putting me in the right direction!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/tkem/cachetools/issues/45#issuecomment-140490321>.
>
Thanks for taking the time to look into this.

Marco
