### ISSUE TITLE
Weird wheel metadata.json

### ISSUE THREAD

**Issue by pombredanne** [tkem/cachetools#72]
See https://bitbucket.org/pypa/wheel/issues/164/space-separated-keywords-are-not-processed
My question: how did you build the wheel you upload to Pypi?
Which exact versions of pip/setuptools/wheel/distlib/Python do you use? and on which OS?

**Comment by tkem** [comment]
OS was Ubuntu 14.04 LTS, but since I recently upgraded to Ubuntu 16.04, I can't tell you the exact versions used at the time any more.

**Comment by pombredanne** [comment]
@tkem Thank you. Do you recall using a virtualenv? or do you usually make global installs for Python packages?

**Comment by tkem** [comment]
@pombredanne: I did not use a virtualenv for building the wheel, but fairly recent (at the time) versions of setuptools/wheel installed using `pip --user`. 

Now that  I had some time to reflect ;-), I noticed the keywords on the PyPI page being messed up by adding
```
from __future__ import unicode_literals
```
to my `setup.py`. I didn't check the wheel, though, but only edited the keywords using the PyPI Web interface. My bad.

Please see #71 and 7f850b8c8fa60ccdeca3ffe865debf2f5f165388 for details.

**Comment by tkem** [comment]
Should be fixed with v2.0.0.

**Comment by pombredanne** [comment]
thanks :)
