### ISSUE TITLE
Support unlimited capacity

### ISSUE THREAD

**Issue by sublee** [tkem/cachetools#73]
In my opinion, unlimited cache capacity that called `maxsize` is useful when we use `TTLCache`.  This cache algorithm has own expiration condition above the size limit.  So it still works as "cache" even though it has no any size limit.  I want to control cache lifetime with only TTL not including the size.

I've already tried to make an unlimited `TTLCache` with `maxsize=float('inf')` and it looks good.  But it wasn't perfect because of `__repr__`:

```python
>>> c = TTLCache(float('inf'), ttl=3)
>>> c['a'] = 123
>>> c.keys()
['a']
>>> c.keys()
[]
>>> c
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../cachetools/ttl.py", line 142, in __repr__
    return cache_repr(self)
  File ".../cachetools/cache.py", line 35, in __repr__
    self.__currsize,
TypeError: %d format: a number is required, not float
```

@tkem, if you agree this about this idea, I'll make a merge request.

**Comment by tkem** [comment]
@sublee: I was thinking about this myself, but decided to drop the idea to keep ``cachetools`` more consistent; for example, 
> a cache is a mutable mapping of a fixed maximum size.

AFAICS what you're basically looking for is some kind of "expiring" dict without a ``maxsize``. I think such a thing might also be quite useful outside of ``cachetools``, so I'd suggest providing this as an independent package. What's more, ``TTLCache`` might then be able to use this for its implementation, much like ``LRUCache`` simply uses ``OrderedDict`` now.

**Comment by tkem** [comment]
With that being said, if it's only about replacing the `℅d` with `℅r` in `__repr__`, that should be doable.

**Comment by sublee** [comment]
@tkem Sounds good.  I'll make a merge request soon.  Thank you for discussing about the suggestion.

**Comment by tkem** [comment]
@sublee: Already done in 4bd1999b4fc30c650a99f01015f3c025613cab5b ;-)

I just have to decide whether I should add a unit test for this, which would make it "officially supported", or if I'd let it pass as an "implementation detail"...

**Comment by sublee** [comment]
@tkem Oh, you were faster.  I think a non-`int` `maxsize` is also a valid `maxsize` if it provides comparison operations like `__gt__` or `__lt__`.  So I vote to "officially supported".

**Comment by sublee** [comment]
Thank you for fixing my issue!

**Comment by tkem** [comment]
Well, better thank me when I manage to release a version on PyPI that includes this ;-)
Should start working on that next week...

**Comment by tkem** [comment]
@sublee: is Python 3.2 compatibility important for you? I plan to drop this in the next release, which will also include this fix.

**Comment by sublee** [comment]
@tkem No I'm using only Python 2.7 and 3.5.  3.2 is too old.

**Comment by tkem** [comment]
Thanks. Stay tuned for cachetools v2.0.0, then ;-)
