### ISSUE TITLE
cachetools in conda-forge

### ISSUE THREAD

**Issue by maartenbreddels** [tkem/cachetools#77]
I'm planning to add my package [vaex](https://github.com/maartenbreddels/vaex) to the conda-forge channel (see https://conda-forge.github.io), but I have cachetools as a dependency. Are you interested in adding it yourself? It's pretty easy, check out the instructions:
https://conda-forge.github.io/#add_recipe
Really nice package btw!

**Comment by tkem** [comment]
Haven't heard of that, and not planning to use it myself.
So thanks, but no thanks ;-)
But please, go ahead as you see fit!

**Comment by maartenbreddels** [comment]
Just to let you know, I did a PR here:
https://github.com/conda-forge/staged-recipes/pull/1725
that ended up in a repo here:
https://github.com/conda-forge/cachetools-feedstock
where you can see it build for osx, linux and win32/64, the files are here:
https://anaconda.org/conda-forge/cachetools/files
Installing cachetools with (ana/mini)conda goes like:
```conda install -c conda-forge cachetools```
In case you also want to be a maintainer in the future, let me know.

**Comment by tkem** [comment]
Looks nice! I really appreciate this, but I try to stay out of packaging/distribution as much as possible ;-)

**Comment by maartenbreddels** [comment]
no problem 👍
