### ISSUE TITLE
Cachetools internals

### ISSUE THREAD

**Issue by freeseacher** [tkem/cachetools#79]
Hi! tnx for cachetools. 
Can you please add some kind of internal view of current states of cache ?
i am talking about for example hit/miss, fullfilnes, min/max ttl in cache 
Our programmers use it heavy in latest code, so i'm as admin want to know how healthy our cache is.
Tnx!

**Comment by tkem** [comment]
Well, no. But this shouldn't be too hard for you to add yourself, using wrapper classes for the cache implementations that keep such statistics.

**Comment by tkem** [comment]
You might want to have a look at the `cachetools.func` implementation for how to keep hit/miss stats, for example.
