### ISSUE TITLE
KeyError TTLCache

### ISSUE THREAD

**Issue by rafaelsimbiose** [tkem/cachetools#80]
Hi, I received KeyError when I attributed the value to cache using TTLCACHE, for example:

I have this cache:

```python
WHITE_LIST_CACHE = TTLCache(maxsize=10000,
                            ttl=10)
```

And error ocurred now:

```python
WHITE_LIST_CACHE[project_id] = white_list
```

This traceback happens when he called self.expire and crash in del self.data[key] into cache_delitem method, he returned KeyError.

```python
def __setitem__(self, key, value, cache_setitem=Cache.__setitem__):
        with self.__timer as time:
            self.expire(time) <---------
            cache_setitem(self, key, value)
        try:
            link = self.__getlink(key)
        except KeyError:
            self.__links[key] = link = _Link(key)
````
--------------------------------------
```python
while curr is not root and curr.expire < time:
            cache_delitem(self, curr.key) <-----
            del links[curr.key]
            next = curr.next
            curr.unlink()
            curr = next
````
--------------------------------------
```python
    def __delitem__(self, key):
        size = self.__size.pop(key)
        del self.__data[key] <------ Exception happens here
        self.__currsize -= size
    def __contains__(self, key):
        return key in self.__data
```
Is this expected?

Thanks !

**Comment by tkem** [comment]
@rafaelsimbiose: No, as far as I can tell from your report, this is *not* expected. Can you provide a test case to reproduce this? Is your code multi-threaded, and you forgot to lock access to `WHITE_LIST_CACHE` properly?

**Comment by rafaelsimbiose** [comment]
@tkem I discovered the problem, it really was something that was not doing the lock with threads, I'll close the issue. Thank so much.

**Comment by tkem** [comment]
You're welcome! Maybe I should state this more prominently in the docs...
