### ISSUE TITLE
add argument for exclude invalid cache

### ISSUE THREAD

**Issue by Zuckonit** [tkem/cachetools#81]
sometimes we do not wanna cache everything, for example when I use decractor ttl_cache like below:

```
import requests
from cachetools.func import ttl_cache

@ttl_cache(maxsize=10, ttl=1000)
def test(url):
    try:
       return requests.get(url).content
    except:
       return None
```

then I do not wanna the invalid value ```None``` to be cached in TTLCache. so I suggest cachetools add some argument for exclude the self-define invalid value

**Comment by tkem** [comment]
I'd rather suggest *not* catching the exception, and converting to `None`  in the caller.
