### ISSUE TITLE
Mistake in #cachetools.cached doc

### ISSUE THREAD

**Issue by slavkoja** [tkem/cachetools#85]
Hi,

in the [cachetools.cached](http://pythonhosted.org/cachetools/#cachetools.cached) is described how to use single cache for multiple functions, but there is small mistake in `import` statement. The line:
```python
from cachetools import cached, hashkey, LRUCache
```
have to be:
```python
from cachetools import cached, LRUCache
from cachetools.keys import hashkey
```
regards

**Comment by tkem** [comment]
Thanks for sharing, I'll fix that as soon as I get back from summer vacation!

**Comment by slavkoja** [comment]
OK, enjoy your vacation! ;-)

**Comment by tkem** [comment]
Documentation has been fixed in master branch, but pythonhosted.org does no longer allow documentation uploads. So you won't see any updates there, until #76 is resolved.
