### ISSUE TITLE
Documentation: clear interest of Cache over a dict

### ISSUE THREAD

**Issue by Aluriak** [tkem/cachetools#87]
I came across [cachetools.cached](http://cachetools.readthedocs.io/en/latest/#cachetools.cached) documentation, and it reads:

> The cache argument specifies a cache object to store previous function arguments and return values. Note that cache need not be an instance of the cache implementations provided by the cachetools module. cached() will work with any mutable mapping type, including plain dict and weakref.WeakValueDictionary.

So, what is the interest of a Cache object over a mutable mapping type like `dict` ?

All the explanations are given in Cache online documentation, but it seems that Cache has basically the same behavior as a `dict` in that particular case.

I think this should be made clear at this point (and maybe in the docstring of [Cache](https://github.com/tkem/cachetools/blob/master/cachetools/cache.py#L18) itself ?).

**Comment by tkem** [comment]
Huh? I'm afraid, I don't understand this...
The difference between a `Cache` and a `dict` should be clear after reading the first two paragraphs or so of the docs... I don't think repeating this for this special decorator function adds any value (as neither does, for this specific case, explainging the difference between a `dict` and a `weakref.WeakValueDictionary` which is also mentioned as a possible candidate).
