### ISSUE TITLE
Statistics on cache

### ISSUE THREAD

**Issue by Aluriak** [tkem/cachetools#88]
I would like to have statistics on cache, like `lru_cache.cache_info` and maybe more.

Before i start implementing anything, do you have any though on the subject ?
Should i add the behaviors directly on classes ? Under a flag condition ? Or maybe a mixin ? Or a dedicated object that would appear in the main API ?

**Comment by tkem** [comment]
This has been brought up before, and my final verdict on it was that statistics will *never* be added to the basic `Cache` classes. So you should try and come up with something that doesn't require modifications to any existing classes or functions, like the `func` decorators. But why not just use these, then?

**Comment by tkem** [comment]
Actually, I'm thinking about splitting `cachetools.func` out into its own package. So I'd suggest you do the same with whatever you come up with regarding your statistics. Thus you can publish and maintain it in your own.
