### ISSUE TITLE
Drop Python 3.3 support?

### ISSUE THREAD

**Issue by tkem** [tkem/cachetools#93]
It seems to be a reasonable (and somewhat common) strategy to limit support to the last three Python 3 minor versions. Adhering to semver might become a hassle, though...

**Comment by hugovk** [comment]
Python 3.3 is EOL and no longer receiving security updates, so dropping it sounds sensible.

**Comment by tkem** [comment]
@hugovk: Probably, just thinking whether this would require me to bump cachetools version to 3.0.0 or not...

**Comment by hugovk** [comment]
If you're following semver: yes, bump to 3.0.0, 

If not following semver: probably yes too. 

Let version numbers be your tool and work for you. They help communicate to users.

**Comment by tkem** [comment]
What bugs is that following this scheme, for every *minor* Python 3 release, I'll have to eventually bump the *major* version of cachetools. Doesn't feel right, somehow.

**Comment by hugovk** [comment]
How do you mean exactly?

Bump micro for bug fixes. 

Bump minor for new features (plus bug fixes).   

Bump major for non-backwards compatible things (plus bug fixes or new features).

To add compatibility for a new Python 3.x is a new feature, so a minor release. 

Dropping an old Python 3.x is non-backwards compatible, so a major release. The major bump gives users notice that they should check before upgrading, as it may break things for them.

**Comment by tkem** [comment]
Dropped with cachetools v3.0.0.
