### ISSUE TITLE
caching with mutable arguments

### ISSUE THREAD

**Issue by skirpichev** [tkem/cachetools#98]
There are couple of reasons to implement that.

First, sometimes it just doesn't matter if function arguments are mutable or not.  For example, we may only care if the argument implements read-only sequence protocol, as tuple - function will work in same way for list.

Next, mutable arguments may be  used for efficiency reasons, even for mathematical functions.

Not sure, if there are no better alternatives, but probably pickle may be used to implement requested feature.  (And that "battery" is included to the stdlib.)
```
In [11]: def pickle_key(*args, **kwargs):
    ...:     return cachetools.keys.hashkey(pickle.dumps(args, 1) + pickle.dumps(kwargs, 1))
    ...: 
```
Serialization protocol looks to be a natural way to express a temporary "freeze" of the object structure.

**Comment by tkem** [comment]
See #97. Pickle is a bad way to do this, since it's representation is not distinct, e.g. the "same" `dict` may have different pickle representations depending on insertion order, etc.
So I don't thinks there's a "one size fits all" solution to this. Depending on your requirements and invariants, it's probably best to create a custom cache key for each application.

**Comment by skirpichev** [comment]
> See #97. 

Oh, sorry for posting.  Definitely, I used wrong keywords to search first.

> Pickle is a bad way to do this, since it's representation is not distinct, e.g. the "same" dict may have different pickle representations

I don't sure if that's a fatal issue.  Yes, maybe there will be more cache misses.  But nothing more dangerous, if user function take into account orderless nature of dict.

> it's probably best to create a custom cache key for each application.

Yes, something specialized may be more suitable to each case, but I see no harm in providing a very generic solution.  Please reconsider (and reopen either this or #97).

Another option coming in mind: provide some protocol, that users may implement to offer immutable views for mutable data.  And use this in some key function.  AFAIR, there was a PEP to implement the freeze protocol.

**Comment by skirpichev** [comment]
@tkem, also I'm not sure that "dict order mystery", mentioned in [SO thread](https://stackoverflow.com/questions/23069908/pickle-serialization-order-mystery) is not py2-specific.  At least, I can't reproduce something like this on py3.5 or above.

**Comment by skirpichev** [comment]
> will always result in the same representation if its set of (key, value) pairs are identical. Please correct me, if I'm wrong.

I don't know yet for sure.  Can't find issues on b.p.o, related to this problem.  Maybe there are something in old "what's new".  But for py3 (since 3.5 at least) this problem seems to be absent.

> So a cache key based on pickle is out of the question

Even if there is no issue for py3?

> since it will work in some cases, but won't work in others

If "other cases" could be well documented - why not?

**Comment by tkem** [comment]
Please submit a proper PR including unit tests showing your proposed feature works on both Python 3 _and_ Python 2.7. Then we'll talk. Until then - case closed.
